### ISSUE TITLE
Wrong Kernel Pod IP being assigned on Kernel Restart on K8s runtime

### ISSUE THREAD

**Issue by rahul26goyal** [jupyter/enterprise_gateway#1012]
## Description
We have deployed JEG on Kubernetes cluster and trying to run `spark_python_kubernetes` and `python_kubernetes` kernel using it. We are seeing an issue with Kernel restart operation for `spark_python_kubernetes`:

1. On Kernel restart, we see an intermittent issue where JEG does not connect to the New Kernel Driver Pods and rather registers one of the executor / driver pods from previous session if still available. This leads to kernel restart failure as all the further communication with the Kernel happens with the wrong Pod IP and it times out. 
2. Further, when we ( from Notebook UI) sends `shutdown` request for the same kernel, that too fails if a executor IP gets assigned in the above scenario.

**Upon debugging further and looking at the logs,** I found that the `label_selector` that is   being used in code to select the Kernel Driver Pods has issue incase of `spark_*` kernels .   The code only uses `kernel_id=k123` to select kernel pods which ends up selecting all the driver and executor pod running with that `kernel_id` and the first object from the list gets selected as Kernel Pod. This creates randomness and sometimes executor or previous driver pod gets selected if its not deleted yet. 
[KubernetesProcessProxy:get_container_status()](https://github.com/jupyter/enterprise_gateway/blob/master/enterprise_gateway/services/processproxies/k8s.py#L61) Code Block.
The issue does not seem to happen on `python_kubernetes` kernel as its a single pod kernel.

### How does the driver and executor get the labels?
- Its coming from the kernel spec file: [kernel.json](https://github.com/jupyter/enterprise_gateway/blob/master/etc/kernelspecs/spark_python_kubernetes/kernel.json#L15)

```
"env": {
    "SPARK_HOME": "/opt/spark",
    "SPARK_OPTS": "--master k8s://https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT} --deploy-mode cluster 
    --name ${KERNEL_USERNAME}-${KERNEL_ID} --conf spark.kubernetes.namespace=${KERNEL_NAMESPACE} --conf spark.kubernetes.driver.label.app=enterprise-gateway     --conf spark.kubernetes.executor.label.component=kernel        --conf spark.kubernetes.driver.label.component=kernel 
 *# Driver and executor labels added. >>>>>>>>>>>>>*
    --conf spark.kubernetes.driver.label.app=enterprise-gateway
    --conf spark.kubernetes.driver.label.kernel_id=${KERNEL_ID} 

    
    --conf spark.kubernetes.executor.label.app=enterprise-gateway
    --conf spark.kubernetes.executor.label.kernel_id=${KERNEL_ID} 

        --conf spark.kubernetes.driver.container.image=${KERNEL_IMAGE} --conf spark.kubernetes.executor.container.image=${KERNEL_EXECUTOR_IMAGE} 
    --conf spark.kubernetes.authenticate.driver.serviceAccountName=${KERNEL_SERVICE_ACCOUNT_NAME} --conf spark.kubernetes.submission.waitAppCompletion=false --conf spark.kubernetes.pyspark.pythonVersion=3 ${KERNEL_EXTRA_SPARK_OPTS}",
    "LAUNCH_OPTS": ""
  },
```
**Both driver and executor pods have `kernel_id` label assigned.**

## Screenshots / Logs

Here are the details of a Kernel with ID: `3e7112ea-a104-4c76-bb08-3c2ef96f9325:d01bc549-19c37ab9f89058da4840ffe7` for which I have captured the detailed logs. 

### Kernel Pod Details
```
# old kernel pods.
name                         
k3e7112ea-a104-4c76-bb08-3c2ef96f9325-17cb3c7d0f61e624-exec-3   1/1     Running     0          87m     192.168.113.139   ip-192-168-127-71.us-west-2.compute.internal    <none>           <none>
k3e7112ea-a104-4c76-bb08-3c2ef96f9325-17cb3c7d0f61e624-exec-4   1/1     Running     0          87m     192.168.101.128   ip-192-168-101-31.us-west-2.compute.internal    <none>           <none>
# old kernel driver pod
*k3e7112ea-a104-4c76-bb08-3c2ef96f9325-8103d17d0f5b41c2-driver   0/2     Completed   0          95m     192.168.145.81*    ip-192-168-152-96.us-west-2.compute.internal    <none>           <none>

# new Kernel upon restart
*k3e7112ea-a104-4c76-bb08-3c2ef96f9325-c439d27d0f61b0b4-driver   2/2     Running     0          88m     192.168.111.104*   ip-192-168-110-92.us-west-2.compute.internal    <none>           <none>
```
From the above output: 
- Old driver IP: 192.168.145.81
- new driver IP: 192.168.111.104

### JEG logs with inline comments:

```
<<<<<<<<<<<<<<<<<<<<<<<<<<<# closing existing connection with the Kernel

[D 2021-11-11 14:23:15.715 EnterpriseGatewayApp] Websocket closed 3e7112ea-a104-4c76-bb08-3c2ef96f9325:d01bc549-19c37ab9f89058da4840ffe7
[I 2021-11-11 14:23:15.716 EnterpriseGatewayApp] Starting buffering for 3e7112ea-a104-4c76-bb08-3c2ef96f9325:d01bc549-19c37ab9f89058da4840ffe7
[D 2021-11-11 14:23:15.716 EnterpriseGatewayApp] Clearing buffer for 3e7112ea-a104-4c76-bb08-3c2ef96f9325

<<<<<<<<<<<<<<<<<<<<<<<<<<<# restart request initiated..*
[D 2021-11-11 14:23:16.727 EnterpriseGatewayApp] Shutdown request sent to listener via gateway communication port.
[D 2021-11-11 14:23:17.828 EnterpriseGatewayApp] KubernetesProcessProxy.terminate_container_resources, pod: rhgoyal-endpoint.k3e7112ea-a104-4c76-bb08-3c2ef96f9325-6442437d0f5b75ba-exec-1, kernel ID: 3e7112ea-a104-4c76-bb08-3c2ef96f9325 has been terminated.
[D 2021-11-11 14:23:17.830 EnterpriseGatewayApp] Shutdown request sent to listener via gateway communication port.
# old kernel shutdown completed in 2 secconds..

<<<<<<<<<<<<<<<<<<<<<<<<<<< # Starting new kernel for the same Kernel IP

[D 2021-11-11 14:23:17.830 EnterpriseGatewayApp] Instantiating kernel 'PySpark (Kubernetes)' with process proxy: enterprise_gateway.services.processproxies.k8s.KubernetesProcessProxy
[D 2021-11-11 14:23:17.831 EnterpriseGatewayApp] Response socket launched on '192.168.109.162:58043' using 5.0s timeout
[D 2021-11-11 14:23:17.831 EnterpriseGatewayApp] Starting kernel: ['/usr/local/share/jupyter/kernels/spark_python_kubernetes/bin/run.sh', '--RemoteProcessProxy.kernel-id', '3e7112ea-a104-4c76-bb08-3c2ef96f9325', '--RemoteProcessProxy.response-address', '192.168.109.162:58043', '--RemoteProcessProxy.spark-context-initialization-mode', 'lazy']


# <<<<<<<<<<<<<<<<<<<<<<<<<<< waiting on kernel pod status -> picks up an executor Pod
[D 2021-11-11 14:23:18.388 EnterpriseGatewayApp] 1: Waiting to connect to k8s pod in namespace 'rhgoyal-endpoint'. Name: 'k3e7112ea-a104-4c76-bb08-3c2ef96f9325-6442437d0f5b75ba-exec-2', Status: 'Pending', Pod IP: 'None', KernelID: '3e7112ea-a104-4c76-bb08-3c2ef96f9325'

<<<<<<<< # still waiting  : Picks up a different executor-pod but this pod satisfied the `Running` state criteria

[D 2021-11-11 14:23:27.797 EnterpriseGatewayApp] 9: Waiting to connect to k8s pod in namespace 'rhgoyal-endpoint'. Name: 'k3e7112ea-a104-4c76-bb08-3c2ef96f9325-17cb3c7d0f61e624-exec-3', Status: 'Running', Pod IP: '192.168.113.139', KernelID: '3e7112ea-a104-4c76-bb08-3c2ef96f9325'

# since the pod is in running state, JEG registers this Pod's IP as new kernel IP.

[D 2021-11-11 14:23:30.574 EnterpriseGatewayApp] Received Payload 'Si9wEwPae5nBdejXkeqhaKffw5lGaZYy7t1FXlkGBYhfFuKNq843lLvHgrP642qJFzFmEY7bxyHN3gnDtEideEk0FRs4xZ4Dt51am7VCykgeE3wu8fQKu20TpCC6Dn4S+Oe0izrnHzACRLAEzEs+72s484v4IoZj5TsLzRvODB233IeDK2Sm64Yy3NrYmPA2EDR04dseKpJvz7LAPQ+g5RKutWoF6EonizIPA9TTQKv8kO24EE6y31bdkxqu9TPu/z+DY18IW+OH84snfJ1WPQt7dZV2RsJ9TBZutQjkXtNVdYloUZUHisKrkEnTFrvq1lvNRqPtrZ8pwLJ7ka4tIQtyNTVyJaFXKksgHr8LWeQUn4eIIB9NNaJb63a+RgWm8y1WX3p10BDp+jhjOk89tg=='
[D 2021-11-11 14:23:30.574 EnterpriseGatewayApp] Decrypted Payload '{"shell_port": 33285, "iopub_port": 33065, "stdin_port": 34047, "control_port": 55775, "hb_port": 45715, "ip": "0.0.0.0", "key": "32c3b119-b841-49f6-8f21-4d7957df4465", "transport": "tcp", "signature_scheme": "hmac-sha256", "kernel_name": "", "pid": "64", "pgid": "20", "comm_port": 43135}'
[D 2021-11-11 14:23:30.575 EnterpriseGatewayApp] Connect Info received from the launcher is as follows '{'shell_port': 33285, 'iopub_port': 33065, 'stdin_port': 34047, 'control_port': 55775, 'hb_port': 45715, 'ip': '0.0.0.0', 'key': '32c3b119-b841-49f6-8f21-4d7957df4465', 'transport': 'tcp', 'signature_scheme': 'hmac-sha256', 'kernel_name': '', 'pid': '64', 'pgid': '20', 'comm_port': 43135}'
[D 2021-11-11 14:23:30.575 EnterpriseGatewayApp] Host assigned to the Kernel is: 'k3e7112ea-a104-4c76-bb08-3c2ef96f9325-17cb3c7d0f61e624-exec-3' '192.168.113.139'
[D 2021-11-11 14:23:30.575 EnterpriseGatewayApp] Established gateway communication to: 192.168.113.139:43135 for KernelID '3e7112ea-a104-4c76-bb08-3c2ef96f9325'
[D 2021-11-11 14:23:30.575 EnterpriseGatewayApp] Updated pid to: 64
[D 2021-11-11 14:23:30.576 EnterpriseGatewayApp] Updated pgid to: 20
[D 2021-11-11 14:23:30.577 EnterpriseGatewayApp] Received connection info for KernelID '3e7112ea-a104-4c76-bb08-3c2ef96f9325' from host 'k3e7112ea-a104-4c76-bb08-3c2ef96f9325-17cb3c7d0f61e624-exec-3': {'shell_port': 33285, 'iopub_port': 33065, 'stdin_port': 34047, 'control_port': 55775, 'hb_port': 45715, 'ip': '192.168.113.139', 'key': '32c3b119-b841-49f6-8f21-4d7957df4465', 'transport': 'tcp', 'signature_scheme': 'hmac-sha256', 'kernel_name': '', 'comm_port': 43135}...
[D 2021-11-11 14:23:30.577 EnterpriseGatewayApp] Connecting to: tcp://192.168.113.139:55775
[D 2021-11-11 14:23:30.578 EnterpriseGatewayApp] Connecting to: tcp://192.168.113.139:33065
[D 2021-11-11 14:23:30.581 EnterpriseGatewayApp] Refreshing kernel session for id: 3e7112ea-a104-4c76-bb08-3c2ef96f9325
[I 2021-11-11 14:23:30.581 EnterpriseGatewayApp] Kernel restarted: 3e7112ea-a104-4c76-bb08-3c2ef96f9325
[D 2021-11-11 14:23:30.581 EnterpriseGatewayApp] Connecting to: tcp://192.168.113.139:33285
[D 2021-11-11 14:23:30.583 EnterpriseGatewayApp] Buffering msg on 3e7112ea-a104-4c76-bb08-3c2ef96f9325:iopub
[D 2021-11-11 14:23:30.585 EnterpriseGatewayApp] Buffering msg on 3e7112ea-a104-4c76-bb08-3c2ef96f9325:iopub
[D 2021-11-11 14:23:30.594 EnterpriseGatewayApp] Buffering msg on 3e7112ea-a104-4c76-bb08-3c2ef96f9325:iopub
[D 2021-11-11 14:23:30.595 EnterpriseGatewayApp] Buffering msg on 3e7112ea-a104-4c76-bb08-3c2ef96f9325:iopub


# here it gets interesting...timeout occurns ..no the activity status log line either.

[W 2021-11-11 14:23:35.584 EnterpriseGatewayApp] Timeout waiting for kernel_info_reply: 3e7112ea-a104-4c76-bb08-3c2ef96f9325
[E 2021-11-11 14:23:35.585 EnterpriseGatewayApp] Exception restarting kernel
    Traceback (most recent call last):
      File "/emr/notebook-env/lib/python3.7/site-packages/notebook/services/kernels/handlers.py", line 83, in post
        yield maybe_future(km.restart_kernel(kernel_id))
      File "/emr/notebook-env/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/emr/notebook-env/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/emr/notebook-env/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 345, in restart_kernel
        yield future
      File "/emr/notebook-env/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
    tornado.util.TimeoutError: Timeout waiting for restart
 # returning timeout to NB with 500 statu scode.
[E 211111 14:23:35 web:2243] 500 POST /api/kernels/3e7112ea-a104-4c76-bb08-3c2ef96f9325/restart (127.0.0.1) 18901.99ms

```

## Environment

- Enterprise Gateway Version [v2.1.0]
- Platform:  Kubernetes]
- Others [Jupyter Notebook]

## Proposed Solutions
Based on the analysis, I propose the following solutions to fix the problem and we can discuss which one aligns better both in terms on maintenance and compatibility:

### 1. Remove `kernel_id` label from Executor pods
This could be a simple fix so that JEG does not end up selecting the Executor pods when trying to filter the kernel pods. 
Cons:
1. This will break backward incompatibility of JEG. 
2.  People might have build other solutions based on these labels to track metrics related to a particular kernel session.
Thus, removing the existing label does not seem like a good idea. 

### 2. Introduce a new Label:
We could introduce a new label which will be added only to: say 
```
kernel-component: main-kernel
```
1. Spark Driver pods and not executor pods. `--conf spark.kubernetes.driver.label.kernel-component=main-kernel`
2. All the singe pod vanilla language kernels like python,R and scala etc.  ( [needs updating template file](https://github.com/jupyter/enterprise_gateway/blob/9719e6f9641d42013839ea4311cdfd6147a98e5c/etc/kernel-launchers/kubernetes/scripts/kernel-pod.yaml.j2))

To keep the code backward compatible, we can introduce a new Environment variable though which this new label 
will be made available to JEG runtime. 
```
EG_K8S_EXTRA_KERNEL_LABELS="kernel-component=main-kernel"
```
The code on `KubernetesProcessProxy:get_container_status()` can check if this environment variable is available and append to the `label_selector` parameter. 

or we can update the existing `label_selector` to hardcode this new label in code.

@kevin-bates and others: let me know your thoughts on this and I could start working on the right solution. I am interested to take it up  :) 

Thanks
Rahul Goyal

**Comment by kevin-bates** [comment]
Hi @rahul26goyal - thank you so much for opening this issue and providing such great details!  I agree with your analysis and proposed (second) solution.  I think it's important we retain the kernel_id label which should encompass all associated resources.

Regarding the label, I'm wondering if we could simply _drop_ the `component=kernel` from the executors and filter the `get_container_status` code to apply to only those pods that also have the `component=kernel` label.  This way, no additional label is required and the only changes are for those k8s-spark-based kernelspecs. (I suppose there could be some backwards compatibility issues for anyone leveraging `component=kernel` on executor pods, but I suspect that would be quite rare (if at all).)

If others are uncomfortable removing the `component` label from executors, then I'd rather add some kind of boolean-valued label, like `primary` or `controller`, to all (regular) kernel and driver pods.

I'm also not sure how this might affect the custom resource definition additions made in #991 and am cc'ing @abzymeinsjtu.  I suspect this should be fine.  Since it includes its own template, any _new_ labelling would need to be included there as well.

**Comment by rahul26goyal** [comment]
hey @kevin-bates : 
yeah, I too had a thought about removing the `component=kernel` from executor as an option but as you said correctly, the the problem is backward compatibility issue that might arise. 

I like the idea of adding `controller=True` as the new label too. 👍

**Comment by kevin-bates** [comment]
Thanks for your comment Rahul.  I still find myself leaning toward removing `component=kernel` from executors.  In fact, one could argue that such a label on executors is incorrect since the kernel is really only the driver.

I suppose we could keep `component` on executors but with a different value, like `executor` or `auxiliary` or `worker`.  (if we adopt this approach, I'd prefer not to use `executor` since that is specific to Spark and we may find this label value useful in other places.)

**Comment by rahul26goyal** [comment]
Thanks @kevin-bates for the quick response.
Based on the suggestion from @kevin-bates, here is the updated proposal:
## Proposed Solution: 3. Modify the Existing Spark Executor label
1. Currently, both driver and executors are assigned a label `component=kernel `. We will modify only the executor label from `component=kernel ` to `component=worker`. ( `--conf spark.kubernetes.executor.label.component=worker`)
2. Append `component=kernel` to the existing `label_selector` used in `get_container_status ` code.

### Pros:
1. This solution would not require any change in existing vanilla language kernels as they already has the label `component=kernel` set in the template.

2. We will also have an unique label `component=worker` which can be used for executor level data collection. 
### Cons:
1. Might break backward compatibility where customers might be using label `component=kernel` to do some data collection and aggregation. But we have an alternate fixed label `spark.kubernetes.driver.label.app=enterprise-gateway` which is already available to both executor and driver.

**Comment by rahul26goyal** [comment]
@kevin-bates : 
I ran into another interesting issue on my setup (old setup without the fix discussed in this ticket) today where I was observing random Spark Python Kernel Restart from JEG.

```
# >>>>>>>>>>>>>>>>>>> the below log line was added by me
[I 2021-12-02 15:09:07.934 EnterpriseGatewayApp] poll call in KubernetesProcessProxy:get_container_status....returning False

# >>>>>>>>>>>>>>>>>>>  this shows that JEG triggers Kernel restart
[I 2021-12-02 15:09:07.934 EnterpriseGatewayApp] KernelRestarter: restarting kernel (1/5), new random ports
[W 2021-12-02 15:09:07.934 EnterpriseGatewayApp] Remote kernel (3c5dceef-4128-4a5a-99d6-a5f95082b8d8) will not be automatically restarted since there are no clients connected at this time.
[D 2021-12-02 15:09:07.935 EnterpriseGatewayApp] Clearing buffer for 3c5dceef-4128-4a5a-99d6-a5f95082b8d8
[I 2021-12-02 15:09:07.935 EnterpriseGatewayApp] Kernel shutdown: 3c5dceef-4128-4a5a-99d6-a5f95082b8d8

```
Upon debugging the issue, I found this was happening due to **healthcheck** / `KernelRestarter::poll()` function failure. 
The code in JEG which is responsible for executing the `poll()` call is [ ContainerProcessProxy::poll()](https://github.com/jupyter/enterprise_gateway/blob/master/enterprise_gateway/services/processproxies/container.py#L109)   which further relies on `KubernetesProcessProxy:get_container_status()` call to fetch the current status of Kernel. 

We already know the `KubernetesProcessProxy:get_container_status()` might end up returning the status of either of the driver / executors running currently. So, in the unhappy scenario it was picking up an Executor pod which was in `Terminating` state and the call to `ContainerProcessProxy::poll()` was returning `False`. 

```
ContainerProcessProxy::poll()
def poll(self):
        """Determines if container is still active.
        Submitting a new kernel to the container manager will take a while to be Running.
        Thus kernel ID will probably not be available immediately for poll.
        So will regard the container as active when no status is available or one of the initial
        phases.
        Returns
        -------
        None if the container cannot be found or its in an initial state. Otherwise False.
        """
        result = False

        container_status = self.get_container_status(None)
        # Do not check whether container_status is None
        # EG couldn't restart kernels although connections exists.
        # See https://github.com/jupyter/enterprise_gateway/issues/827
        if container_status in self.get_initial_states():
            result = None

        return result
```
Thus, the `KernelRestarter::is_alive` also returned `False`  and the Kernel restart hook got triggered. 

But with this fix that we have in this ticket, I do not not see random Kernel Restart happening anymore.
I think this is because   `KubernetesProcessProxy:get_container_status()` would never return the status of any executor Pod and always return the actual Kernel Pod which will be in running state unless driver is actually terminating. 

let me know your thoughts on this observation. 
Thanks!

**Comment by kevin-bates** [comment]
Hi @rahul26goyal - this is an excellent analysis and seems very similar to that in the original description.  I agree with your assessment.  Thank you.
