### ISSUE TITLE
Pass `base_url` config to Tornado constructor for access in the request handler

### ISSUE THREAD

**Issue by ricklamers** [jupyter/enterprise_gateway#1017]
## Description

I ran into the issue of the `/api/kernelspecs` endpoint returning invalid resource paths for the returned kernels (ones that ignore the configured `base_url`).

More details about the problem can be found here: https://github.com/jupyterlab/jupyterlab/issues/11527

I think `self.base_url` should be passed in the Tornado constructor here:

https://github.com/jupyter/enterprise_gateway/blob/6868fb46d07cdad862f65ed183104db1c3773783/enterprise_gateway/enterprisegatewayapp.py#L186

Since it's consumed in:

https://github.com/jupyter/enterprise_gateway/blob/1b7ecedcb60d109eac2740d5a6195bb7b56c0a5b/enterprise_gateway/services/kernelspecs/handlers.py#L87

when `self` is passed to `kernelspec_model`

https://github.com/jupyter/notebook/blob/601ac0e4f4ccf630f0ac8943411992790e419797/notebook/services/kernelspecs/handlers.py#L21

Let me know if you want me to open a PR for the change.

## Environment

- Enterprise Gateway Version: 2.x
- Platform: not relevant

**Comment by kevin-bates** [comment]
Hi @ricklamers - your analysis looks correct.  Please open a PR.  Since both Kernel Gateway and Enterprise Gateway probably exhibit this issue, a PR to both repos would be appreciated (EG broke its dependency on JKG a release or two ago).  Thank you.

**Comment by kevin-bates** [comment]
Closing via #1019
