### ISSUE TITLE
Why is the environment variable when starting the enterprise gateway not passed to the notebook kernel

### ISSUE THREAD

**Issue by icankeep** [jupyter/enterprise_gateway#1022]
server: 

```
export GATEWAY_EXPORT_ENV=foo
jupyter enterprisegateway --ip=0.0.0.0 --port_retries=0 --port=8414
```

client: 
```
jupyter notebook --gateway-url=http://host:port --GatewayClient.http_user=guest --GatewayClient.http_pwd=guest-password
```

![image](https://user-images.githubusercontent.com/39434627/147648977-8b92af38-e49a-4f35-87ba-5fd4c78ee4db.png)

**Comment by kevin-bates** [comment]
Hi @icankeep.  Because Enterprise Gateway is intended to service requests from multiple clients, the environment of the EG process is not made available to the launched kernel.  Instead, any server-originating envs must be explicitly listed by name in order for their values to be made available to launched processes.  This is accomplished by setting the `EnterpriseGatewayApp.env_process_whitelist` configurable, either on the command line, configuration file, or via the `EG_ENV_PROCESS_WHITELIST` environment variable.

```
--EnterpriseGatewayApp.env_process_whitelist=<list-item-1>...
    Environment variables allowed to be inherited from the spawning process by
    the kernel. (EG_ENV_PROCESS_WHITELIST env var)
    Default: []
```

Also note that _any_ `KERNEL_`-prefixed envs set on the _client_ will be propagated from the client, through the server, and on to the kernel process as well.

I hope that helps.

**Comment by icankeep** [comment]
```
jupyter enterprisegateway --ip=0.0.0.0 --port_retries=0 --port=8414 --EnterpriseGatewayApp.env_whitelist=*
```

I start the service according to the configuration, but the following error is reported:
```
The 'env_whitelist' trait of an EnterpriseGatewayApp instance must be a list, but a value of class 'str' (i.e. '*') was specified.
```

**Comment by icankeep** [comment]
I tried the following configuration, but it didn't work too.

```
jupyter enterprisegateway --ip=0.0.0.0 --port_retries=0 --port=8414 --EnterpriseGatewayApp.env_whitelist=['*']
```

**Comment by kevin-bates** [comment]
Hi.  A few observations and suggestions:
1. The configurable option you want is `env_process_whitelist` not `env_whitelist`.  The latter is used to filter envs that come across in the kernel start request (from the client), whereas `env_process_whitelist` is used to filter envs set in the EG process.
2. Setting list-valued options via the command line can be tricky[1].  I would suggest using a configuration file[2] or using the `EG_ENV_PROCESS_WHITELIST` env (e.g., `export EG_ENV_PROCESS_WHITELIST=VAR1,VAR2; jupyter enterprisegateway ...` will transfer the envs `VAR1` and `VAR2` from the EG process to the kernel process).
3. The wildcard '*' is not currently supported relative to `env_process_whitelist`.


[1] - You need to quote the brackets (and, separately, items - although I can't recall if the items require their own single quotes or not.) (e.g., `jupyter enterprisegateway --EnterpriseGatewayApp.env_process_whitelist="['VAR1','VAR2']"`). Also, the quoted form is deprecated and can be replaced with separate options - one for each item: `jupyter enterprisegateway --EnterpriseGatewayApp.env_process_whitelist=VAR1 --EnterpriseGatewayApp.env_process_whitelist=VAR2`

[2] - An example configuration file (with options commented out) can be created using `jupyter enterprisegateway --generate-config`.  You would then uncomment the following line and add your desired values:
```python
c.EnterpriseGatewayApp.env_process_whitelist = ["VAR1", "VAR2"]
```

**Comment by kevin-bates** [comment]
Closing.  If there's a direct correlation to something not working in EG, we can re-open at that time.
