### ISSUE TITLE
Determine appropriate packages for vanilla Scala kernel image

### ISSUE THREAD

**Issue by kevin-bates** [jupyter/enterprise_gateway#371]
Since the Scala (Toree) kernel is so tightly coupled with Spark, it could make sense to use the same image for both spark and non-spark (vanilla) modes.  However, at a minimum, we should come up with a list of common data science packages used in Scala kernels and ensure the image contains those.

If we find it best to create separate images, then we can do so as part of this issue.

This issue is related to #367

**Comment by lresende** [comment]
I don't think we need anything special on the image, as the magics available on Toree should handle these additions (%addJar, %addDeps) and customizations to SPARK_OPTS also can make dependencies available on the global classpath.
