### ISSUE TITLE
Unable to start jupyter enterprisegateway

### ISSUE THREAD

**Issue by praveenkanamarlapudi** [jupyter/enterprise_gateway#434]
Hi,

I tried installing `jupyter-enterprise-gateway` and started jupyter with `jupyter enterprisegateway` command. When I try to access from web, I am seeing below error. Please help if I am missing anything.

```(py3) ➜  ~  jupyter enterprisegateway

[I 2018-09-09 20:44:28.982 EnterpriseGatewayApp] Jupyter Enterprise Gateway at http://127.0.0.1:8888
[W 180909 20:44:31 web:2162] 404 GET / (127.0.0.1) 2.62ms
[W 180909 20:44:32 web:2162] 404 GET /favicon.ico (127.0.0.1) 0.75ms
```

**Comment by kevin-bates** [comment]
@praveenkanamarlapudi - This output looks normal.  Looks like some application is attempting to access `/` and `/favicon.ico` - which are not supported endpoints.

How are you trying to access the gateway?  The typical use case is to use a Notebook server that has been extended with the [NB2KG server extension](https://github.com/jupyter-incubator/nb2kg).  We provide a docker image with this all set up if necessary at [elyra/nb2kg](https://hub.docker.com/r/elyra/nb2kg/).

I would also suggest you enable DEBUG logging for the Enterprise Gateway - at least initially.  To do this, add `--log-level=DEBUG` to your command line.  Next, once you have an NB2KG-enabled Notebook pointing at the gateway (via `KG_URL`), refresh the notebook files view and you should see the set of deployment kernelspecs show up in the debug logging in the gateway log.  That will confirm your client is fully talking to your gateway.

Following that will be configuring your kernelspecs for remote usage (if necessary).  We provide several examples in our [kernelspecs tar file](https://github.com/jupyter-incubator/enterprise_gateway/releases/tag/v1.0.0).  However, please note that if you're running on a python 3.x server, you will likely need [this PR](https://github.com/jupyter-incubator/enterprise_gateway/pull/436), that we hope to deliver in a 1.0.1 patch later today. 

I hope that helps.

**Comment by ziedbouf** [comment]
@praveenkanamarlapudi most likely you are trying to access the jupyter entreprise gateway from the browser. As @kevin-bates mentioned the typical use case is to use a Notebook server that has been extended with the NB2KG server extension.

**Comment by kevin-bates** [comment]
The NB2KG-enabled Notebook will use the `KG_URL` environment variable to determine where to forward kernel management requests.   Please refer to [this section](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/getting-started.html#connecting-a-notebook-to-enterprise-gateway) of our Getting Started page.

**Comment by praveenkanamarlapudi** [comment]
Thanks for the details. Let me explore it.
