### ISSUE TITLE
Python3 Kernel for Kubernetes

### ISSUE THREAD

**Issue by parewa-aswin** [jupyter/enterprise_gateway#487]
Is there a Python3 kernel image for Kubernetes? All runtime images seem to be for Python2. If I need to load it myself, would love to know any base images I should start off with.

**Comment by kevin-bates** [comment]
Hi @parewa-aswin.   Good timing 😃 .  I just updated our kernel-py image to be based on the [jupyter/scipy-notebook image](https://hub.docker.com/r/jupyter/scipy-notebook/) (see #486) but had forgotten to push to docker hub. I just pushed the updated image, so please give [elyra/kernel-py](https://hub.docker.com/r/elyra/kernel-py/) another try as you should find it using python 3.6. 

Let us know how it goes and we'll address this issue accordingly.

Thanks.

**Comment by parewa-aswin** [comment]
Awesome. I'll try the new updated image soon and let you know. Thanks 😃

**Comment by kevin-bates** [comment]
@parewa-aswin - did the updated image work out for you?

**Comment by parewa-aswin** [comment]
@kevin-bates I haven't been able to test the image fully but initial pull didn't have any issues. We can close the issue now. I'll create a new issue if anything comes up. Thanks.

**Comment by kevin-bates** [comment]
Great - thanks for the feedback and checking out Enterprise Gateway!
