### ISSUE TITLE
Kernels are not shutting down in YARN Cluster Mode

### ISSUE THREAD

**Issue by kevin-bates** [jupyter/enterprise_gateway#511]
@amangarg96 - I'm copying your comment from Issue #394 and using it to create a new issue, since the two are not really related.  We can use this issue to get to the bottom of things.  Here is that comment...

Hi,

I am using Jupyter Enterprise Gateway in Yarn Cluster Mode, and launching Jupyter Lab server on a remote Linux box.

I am facing the same 'HTTP 403: Failed to authenticate SSHClient with password-less SSH' issue, and here is the log for the same. 

> [I 2018-12-01 19:45:59.421 EnterpriseGatewayApp] Kernel shutdown: 0836005e-2a6b-4c5a-a825-f49bcdef5f30
> [I 2018-12-01 19:49:56.613 EnterpriseGatewayApp] KernelRestarter: restarting kernel (1/5), keep random ports
> [W 2018-12-01 19:49:56.613 EnterpriseGatewayApp] Remote kernel (d90ff5df-2621-4a36-a0d3-1be2f8da1450) will not be automatically restarted since there are no clients connected at this time.
> [W 2018-12-01 19:49:56.618 EnterpriseGatewayApp] Termination of application 'application_1542713397395_139615' failed with exception: 'Response finished with status: 500. Details: {"RemoteException":{"exception":"WebApplicationException","message":"com.sun.jersey.api.MessageException: A message body reader for Java class org.apache.hadoop.yarn.server.resourcemanager.webapp.dao.AppState, and Java type class org.apache.hadoop.yarn.server.resourcemanager.webapp.dao.AppState, and MIME media type application/octet-stream was not found.\nThe registered message body readers compatible with the MIME media type are:\napplication/octet-stream ->\n  com.sun.jersey.core.impl.provider.entity.ByteArrayProvider\n  com.sun.jersey.core.impl.provider.entity.FileProvider\n  com.sun.jersey.core.impl.provider.entity.InputStreamProvider\n  com.sun.jersey.core.impl.provider.entity.DataSourceProvider\n  com.sun.jersey.core.impl.provider.entity.RenderedImageProvider\n*/* ->\n  com.sun.jersey.core.impl.provider.entity.FormProvider\n  com.sun.jersey.json.impl.provider.entity.JSONJAXBElementProvider$General\n  com.sun.jersey.json.impl.provider.entity.JSONArrayProvider$General\n  com.sun.jersey.json.impl.provider.entity.JSONObjectProvider$General\n  com.sun.jersey.core.impl.provider.entity.StringProvider\n  com.sun.jersey.core.impl.provider.entity.ByteArrayProvider\n  com.sun.jersey.core.impl.provider.entity.FileProvider\n  com.sun.jersey.core.impl.provider.entity.InputStreamProvider\n  com.sun.jersey.core.impl.provider.entity.DataSourceProvider\n  com.sun.jersey.core.impl.provider.entity.XMLJAXBElementProvider$General\n  com.sun.jersey.core.impl.provider.entity.ReaderProvider\n  com.sun.jersey.core.impl.provider.entity.DocumentProvider\n  com.sun.jersey.core.impl.provider.entity.SourceProvider$StreamSourceReader\n  com.sun.jersey.core.impl.provider.entity.SourceProvider$SAXSourceReader\n  com.sun.jersey.core.impl.provider.entity.SourceProvider$DOMSourceReader\n  com.sun.jersey.json.impl.provider.entity.JSONRootElementProvider$General\n  com.sun.jersey.json.impl.provider.entity.JSONListElementProvider$General\n  com.sun.jersey.json.impl.provider.entity.JacksonProviderProxy\n  com.sun.jersey.core.impl.provider.entity.XMLRootElementProvider$General\n  com.sun.jersey.core.impl.provider.entity.XMLListElementProvider$General\n  com.sun.jersey.core.impl.provider.entity.XMLRootObjectProvider$General\n  com.sun.jersey.core.impl.provider.entity.EntityHolderReader\n","javaClassName":"javax.ws.rs.WebApplicationException"}}'.  Continuing...
> [E 2018-12-01 19:49:56.673 EnterpriseGatewayApp] Failed to authenticate SSHClient with password-less SSH
> [W 2018-12-01 19:49:56.673 EnterpriseGatewayApp] Remote signal(15) to '-32518' on host '<ip-of-node-on-cluster>' failed with exception 'HTTP 403: Failed to authenticate SSHClient with password-less SSH'. 

I believe that this has interfered with Kernel lifecycle, and hence I am getting 'orphan kernels'. Orphan kernels are the one for which the spark submit was done, the job goes into running state, but the notebook server does not interact with that kernel, so it does not get shutdown when notebook server is shutdown.

**Comment by kevin-bates** [comment]
Hi @amangarg96.  The `403` issue you're encountering using YARN Cluster Mode is really a side affect stemming from a failure to shutdown the kernel in the first attempt.  In those cases, EG will resort to attempting to issue a remote SSH command to issue a kill directly.  However, if you were to configure password-less SSH, then this issue may have not been detected.  To properly release the resources in use by these kernels, you'll need to terminate them manually - typically via the YARN UI - until getting to the bottom of why the initial shutdown fails.

The real issue is a failure occurring in the initial shutdown attempt - which uses the [YARN client API](https://github.com/toidi/hadoop-yarn-api-python-client) to terminate the YARN application.

>[W 2018-12-01 19:49:56.618 EnterpriseGatewayApp] Termination of application 'application_1542713397395_139615' failed with exception: 'Response finished with status: 500. Details: {"RemoteException":{"exception":"WebApplicationException","message":"com.sun.jersey.api.MessageException: A message body reader for Java class 

So this indicates that YARN is encountering an exception in what looks to be an XML reader class.

I would suggest gathering the YARN application logs (mostly `stdout` and `stderr`) and seeing if there are more clues there.  If you attach those logs, along with the _complete_ Enterprise Gateway log, we can troubleshoot this with others.

A quick google of "javax.ws.rs.WebApplicationException YARN"  yields:  https://community.hortonworks.com/questions/226051/yarn-service-rest-api-genericexceptionhandler-weba.html

As a result, you might try issuing the termination using `curl`, first to reproduce, then again specifying the content type.  We use [this call](https://github.com/jupyter/enterprise_gateway/blob/1.x/enterprise_gateway/services/processproxies/yarn.py#L311) against the [yarn-api-client](https://github.com/toidi/hadoop-yarn-api-python-client/blob/master/yarn_api_client/resource_manager.py#L232) to perform the termination.

It would also be good to know the version of YARN and Spark you're using - since we don't see these issues.

Thanks.

cc: @lresende

**Comment by amangarg96** [comment]
I haven't faced this issue again in the last couple of days, and I haven't been able to find the time to reproduce the issue. 

I'll take this up on Monday again.

That being said, I see a lot less orphan kernels and it would be interesting to see what was changed from my previous configuration.

**Comment by amangarg96** [comment]
STDERR for kernel
```
Using connection file '/tmp/kernel-75782334-241c-467a-9614-d273c3aa07c5_PA5ozK.json' instead of '/root/.local/share/jupyter/runtime/kernel-75782334-241c-467a-9614-d273c3aa07c5.json'
Signal socket bound to host: 0.0.0.0, port: 48039
JSON Payload '{"stdin_port": 51236, "pgid": "10099", "ip": "0.0.0.0", "pid": "10151", "control_port": 46639, "hb_port": 23160, "signature_scheme": "hmac-sha256", "key": <key>, "comm_port": 48039, "kernel_name": "", "shell_port": 12652, "transport": "tcp", "iopub_port": 39252}
Encrypted Payload 'tjHpvr/C1ehfUlRDRJZDNmD4Y+T+mYzyWrwa4U9hZfFkfl4dk1aTDyKGYTnuBXRIGmsOBeiDkPeSptJ7ud5+TOq54oPgdLoMDZhcI9J3qvPwo0/3U40SDDbUwCmFuSrugJjvxFXf+boCSomXPuO1LMfI5L23KYPOoUArqZZoIT9BYMZ9RZ9HE+yN9AsXu8sHC3g/WMMWCpD819Zt5l0lElt884K44tZQvsZub2JEzVIKzzmxrG3ASZdNNdofJEVVUMMnwTimfnQZSfICEasAcVI0uwTF66fbe7fi+ATy1i4S2fsh2durHZADtMXZLHOg7857pm5DgIrkgQWq0naIJ+p8CxpJ4p7MJ38o46G+yXmTTTwnC+XO/GE6tQ0Oz2T4Xs9b72MavwGlSYuA2xKtSw==
/grid/1/yarn/local/usercache/fk-mlp-user/appcache/application_1543928474139_36333/container_e238_1543928474139_36333_01_000001/mlp.mlc.Linux_debian_8_11.py27.mlc-base-xgboost.tar.gz/lib/python2.7/site-packages/IPython/paths.py:69: UserWarning: IPython parent '/home' is not a writable location, using a temp directory.
  " using a temp directory.".format(parent))
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing /tmp/kernel-75782334-241c-467a-9614-d273c3aa07c5_PA5ozK.json
```

**Comment by kevin-bates** [comment]
Is the second log snippet actually `STDOUT`?  This is produced from the launchers and goes to `stdout` on my YARN cluster.

I'm afraid you're going to need to figure out why the exception is happening since I'm unable to reproduce this.  Does this happen on EVERY kernel you start in cluster mode - or only intermittently?

>The real issue is a failure occurring in the initial shutdown attempt - which uses the YARN client API to terminate the YARN application.

>>[W 2018-12-01 19:49:56.618 EnterpriseGatewayApp] Termination of application 'application_1542713397395_139615' failed with exception: 'Response finished with status: 500. Details: {"RemoteException":{"exception":"WebApplicationException","message":"com.sun.jersey.api.MessageException: A message body reader for Java class

>So this indicates that YARN is encountering an exception in what looks to be an XML reader class.

**Comment by amangarg96** [comment]
The second log snippet is from `STDERR` in the kernel logs.

And no, it doesn't happen for every kernel. That exception is raised only for the orphan kernels which sometimes show up. Most of the kernels go either into the finished state because of graceful shutdown of notebooks, or get killed by the Gateway server because of the Culling timeout set by me.

**Comment by amangarg96** [comment]
I did switch to a different node for running my Gateway servers, and I haven't seen this issue since. So I should definitely test whether it was a node issue. 

Would a password-less SSH solve this issue of orphan kernels?

**Comment by kevin-bates** [comment]
It might.  It's essentially sending SIGTERM to the process group.  If the process is still detected, it sends SIGKILL.  I'm assuming the process group is correct (that comes from the launcher that is the target of the spark-submit call.

That said, we should figure out what's going on since the REST api is, by far, the best solution.  The ssh approach is merely a fallback.

**Comment by amangarg96** [comment]
I tried to reproduce the error using `curl`, and observed this -


When I used it without header, i.e `curl -v -X PUT -d '{"state": "KILLED"}' 'http://<ip>:8088/ws/v1/cluster/apps/application_1544747350136_52218/state'`, I got the same error which was seen above (Termination of application exception)

```
*   Trying 10.32.77.243...
* TCP_NODELAY set
* Connected to 10.32.77.243 (10.32.77.243) port 8088 (#0)
> PUT /ws/v1/cluster/apps/application_1544747350136_52218/state HTTP/1.1
> Host: 10.32.77.243:8088
> User-Agent: curl/7.60.0
> Accept: */*
> Content-Length: 19
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 19 out of 19 bytes
< HTTP/1.1 500 Internal Server Error
< Cache-Control: no-cache
< Expires: Tue, 18 Dec 2018 12:22:51 GMT
< Date: Tue, 18 Dec 2018 12:22:51 GMT
< Pragma: no-cache
< Expires: Tue, 18 Dec 2018 12:22:51 GMT
< Date: Tue, 18 Dec 2018 12:22:51 GMT
< Pragma: no-cache
< Content-Type: application/json
< X-Frame-Options: SAMEORIGIN
< Transfer-Encoding: chunked
<
* Connection #0 to host 10.32.77.243 left intact
{"RemoteException":{"exception":"WebApplicationException","javaClassName":"javax.ws.rs.WebApplicationException"}}%
```


But when I did so with headers, i.e `curl -v -X PUT -H "Content-Type: application/json" -d '{"state": "KILLED"}' 'http://10.32.77.243:8088/ws/v1/cluster/apps/application_1544747350136_52218/state'`, it worked
```
*   Trying 10.32.77.243...
* TCP_NODELAY set
* Connected to 10.32.77.243 (10.32.77.243) port 8088 (#0)
> PUT /ws/v1/cluster/apps/application_1544747350136_52218/state HTTP/1.1
> Host: 10.32.77.243:8088
> User-Agent: curl/7.60.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 19
>
* upload completely sent off: 19 out of 19 bytes
< HTTP/1.1 202 Accepted
< Cache-Control: no-cache
< Expires: Tue, 18 Dec 2018 12:23:31 GMT
< Date: Tue, 18 Dec 2018 12:23:31 GMT
< Pragma: no-cache
< Expires: Tue, 18 Dec 2018 12:23:31 GMT
< Date: Tue, 18 Dec 2018 12:23:31 GMT
< Pragma: no-cache
< Content-Type: application/json
< X-Frame-Options: SAMEORIGIN
< Location: http://10.32.77.243:8088/ws/v1/cluster/apps/application_1544747350136_52218/state
< Transfer-Encoding: chunked
<
* Connection #0 to host 10.32.77.243 left intact
{"state":"RUNNING"}%
```

Looking at the requests.put line [here](https://github.com/toidi/hadoop-yarn-api-python-client/blob/c5395432c1ca26ef33d961bfaec6c677f42111dd/yarn_api_client/base.py#L58), it looks like headers aren't being used. Could this be the issue?

**Comment by kevin-bates** [comment]
Yes, I think you're on to something.

cc: @lresende
