### ISSUE TITLE
Python + Spark doesnt contain support for AWS S3

### ISSUE THREAD

**Issue by rayh** [jupyter/enterprise_gateway#523]
```
Py4JJavaErrorTraceback (most recent call last)
/usr/local/share/jupyter/kernel-launchers/python/scripts/launch_ipykernel.py in <module>()
----> 1 df = spark.read.format("csv").option("header", "true").load("s3a://eliiza-sydney-datasets-melb-parking-sensors/parking-sensor-2016.csv")

/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py in load(self, path, format, schema, **options)
    164         self.options(**options)
    165         if isinstance(path, basestring):
--> 166             return self._df(self._jreader.load(path))
    167         elif path is not None:
    168             if type(path) != list:

/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/opt/spark/python/lib/pyspark.zip/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o189.load.
: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2195)
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2654)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:547)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:545)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.immutable.List.flatMap(List.scala:355)
	at org.apache.spark.sql.execution.datasources.DataSource.org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary(DataSource.scala:545)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:359)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2101)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2193)
	... 30 more
```

I suspect I'm missing something obvious here.

**Comment by kevin-bates** [comment]
Hmm - The [base spark images](https://hub.docker.com/r/elyra/spark-py/) were built using the Spark 2.4.0 image builder script.  Not sure how AWS S3 gets added or made available.

Someone will need to dig deeper on this.

**Comment by rayh** [comment]
@kevin-bates Just some thoughts, perhaps this should be opened as a new issue:

I think it would be good to find a way to separate these kernel images from the main repo - would make it easier for people to contribute new ones as well as being able to select which ones you provide in your setup.  I'm not sure how this would work, exactly, but it seems like every image requires a copy of `kernel-launchers` - perhaps that could be distributed as a tgz that anyone can pull into their own image?  There are probably a few other constraints to how a kernel image needs to be setup

I'm also wondering how enterprise_gateway will know which kernels to use - could the whitelist be replaced with an explicit list of kernelspecs to use?  perhaps as a JSON/YAML in s3 or suchlike?  allowing alternatives/extras to be added.  I think there are parts of the kernelspec that are internal (how to launch the kernel) and some metadata parts which I may like to override (such as display name, icon image, etc) 

Perhaps the kernel image could accept `kernel_id` and `response_address` as env variables and is expected to start it's kernel by default (when no args are provided)?  This would allow the kernel spec to be more focused on the metadata and delegate the responsibility of how to start a kernel into the kernel image itself

I think things like this would foster ownership and customisation of kernels by removing the need to understand the whole build process for enterprise_gateway (which, admittedly, is preventing me from doing a PR for the R+Spark image)

**Comment by kevin-bates** [comment]
Not sure if this comment was relative to #522 or not.  Before we talk about image separation, do you have any insight on why AWS S3 isn't working?

I'm going to create another issue and copy your text above into that.

**Comment by rayh** [comment]
Yes, it also relates to #522 - thanks for splitting that out.

**Comment by rayh** [comment]
Im not really sure whats best practice for Spark here.  I think one is supposed to provide additional packages at spark-submit time and they are pulled from maven (or elsewhere) to each node.

**Comment by kevin-bates** [comment]
Sorry, I'm not sufficiently knowledgeable about spark to move this forward. 

@lresende, @alanSTC - focusing on the AWS S3 aspect do you have any ideas?

**Comment by danielchalef** [comment]
The Maven coordinates for the open source Hadoop S3 driver needs to be added as a package dependency:
`spark-submit --packages org.apache.hadoop:hadoop-aws:2.7.0`

Note the above package version is tied to the installed AWS SDK for Java version.

In the Spark application's code, something like the following may also be needed:
```
    hadoop_conf = spark.sparkContext._jsc.hadoopConfiguration()
    hadoop_conf.set("fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem")
    hadoop_conf.set("fs.s3a.access.key", access_id)
    hadoop_conf.set("fs.s3a.secret.key", access_key)
```

Note that when using the open source Hadoop driver, the S3 URI scheme is `s3a` and not `s3` (as it is when using Spark on EMR and Amazon's proprietary EMRFS). e.g. `s3a://bucket-name/`

**Comment by kevin-bates** [comment]
@rayh - I think there's sufficient support in place to close this issue - thanks to @danielchalef's [response above](https://github.com/jupyter/enterprise_gateway/issues/523#issuecomment-455905566), the fact that our [spark-based images (python and R) are now built on our richer non-spark images](https://github.com/jupyter/enterprise_gateway/pull/560), and given we've provided instructions for how to [build your own kernel image](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/docker.html#custom-kernel-images).

If you disagree, please let me know and we'll get it re-opened.
Thanks.

**Comment by tahesse** [comment]
First, sorry for the necro-bump.

I thought I'd add some information on how to improve on the current situation.
From my `SparkApplication` CRD deployment file:
```yaml
  sparkConf:
    spark.driver.extraJavaOptions: "-Divy.cache.dir=/tmp -Divy.home=/tmp"
    spark.jars.packages: "org.apache.hadoop:hadoop-aws:3.2.3,org.apache.spark:spark-hadoop-cloud_2.13:3.2.1,com.amazonaws:aws-java-sdk-bundle:1.12.207"
    spark.hadoop.fs.s3a.endpoint: "http://minio:9000"
    spark.hadoop.fs.s3a.aws.credentials.provider: "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    spark.hadoop.fs.s3a.access.key: "accesskey"
    spark.hadoop.fs.s3a.secret.key: "secretkey"
    spark.hadoop.fs.s3a.path.style.access: "true"
    spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    spark.hadoop.fs.s3a.bucket.all.committer.magic.enabled: "true"
```
Looking at the latest Spark release (3.2.1) for the k8s operator (https://googlecloudplatform.github.io/spark-on-k8s-operator/docs/api-docs.html), there exists the optional `sparkConfigMap` which can be added to the jinja2 template based on whether a condition is set or not.

Finally, add my contents from the `sparkConf` into a k8s ConfigMap which must be set through environmental variables (best idea I can come up with right now...).

I will try to draft a PR for this ASAP, because I also try to supply my spark operator jupyternb's with additional configuration and packages.

**Comment by kevin-bates** [comment]
> I will try to draft a PR for this ASAP, because I also try to supply my spark operator jupyternb's with additional configuration and packages.

This would be much-appreciated @tahesse - thank you!

**Comment by tahesse** [comment]
@kevin-bates Can you point me in the right direction how and where the `KERNEL_*` environmental variables are propagated from the local Jupyter* install to the EG? This would speed things up on my side. I have found https://jupyter-enterprise-gateway.readthedocs.io/en/v1.2.0/config-options.html#per-kernel-environment-overrides but it does not mention where the environmental variables are read. The paragraph in the link says that all `KERNEL_*` variables are read and passed to the kernel start up, I know, but I am curious. 😉 

I'd also like to have your opinion on how to name the env var. Do you think `KERNEL_SPARKAPP_CONFIG_MAP` is appropriate? AFAIU it will load [here](https://github.com/jupyter-server/enterprise_gateway/blob/main/etc/kernel-launchers/operators/scripts/launch_custom_resource.py#L38-L40) and I _simply_ modify the j2 template.

Thank you!

**Comment by kevin-bates** [comment]
> Can you point me in the right direction how and where the KERNEL_* environmental variables are propagated from the local Jupyter* install to the EG?

If using an application that uses Jupyter Server as the "client", the `KERNEL_` and those names configured in `env_whiltelist` are captured and set into the JSON body [here](https://github.com/jupyter-server/jupyter_server/blob/9bd9bdc55e87d867f826b4a3fe36f4a627bd156e/jupyter_server/gateway/managers.py#L417-L433).  If using the REST API directly (or via another application), these need to be set as key-value pairs into the `env` stanza of the start request's body.

> I'd also like to have your opinion on how to name the env var. Do you think KERNEL_SPARKAPP_CONFIG_MAP is appropriate? 

I think the name is fine.

> AFAIU it will load [here](https://github.com/jupyter-server/enterprise_gateway/blob/main/etc/kernel-launchers/operators/scripts/launch_custom_resource.py#L38-L40) and I simply modify the j2 template.

Yes, that's the idea, just reference the lowercase form in the jinja template: `kernel_sparkapp_config_map`.

> Also, if there exists an option to pass this value per spark-operator kernel launch instead of the environmental variable, please let me know! It would be a so much more powerful approach!

Unfortunately, ENVs are the current mechanism for _parameterizing_ kernel launches.  We would like to formally introduce parameterization that will likely be based on JSON schema embedded in the kernelspec responses that contain details of parameters that that particular kernelspec (and kernel provisioner) support.  This would then make these kinds of things generally available to all Jupyter applications that launch kernels, not just those launched via EG.
