### ISSUE TITLE
write_error when kernel doesn't exist

### ISSUE THREAD

**Issue by parewa-aswin** [jupyter/enterprise_gateway#537]
When used in websocket mode, whenever the kernel isn't present and a request is sent like **findById**, a response is sent by the web:
`404 GET /api/kernels/9fd5bb95-7851-4532-af22-4d6b9f94506c/channels?session_id=3f694fa1-eb62-4880-bd06-5c670f57bcc3&token=hvtHMyZ8RfUMNuvpFAgqA13RNtczLEDF (100.96.0.1): Kernel does not exist: 9fd5bb95-7851-4532-af22-4d6b9f94506c`

Whenever this occurs, enterprise gateway shows an error:
`Uncaught exception in write_error
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/tornado/web.py", line 1112, in send_error
        self.write_error(status_code, **kwargs)
      File "/usr/lib/python2.7/site-packages/notebook/base/handlers.py", line 536, in write_error
        html = self.render_template('%s.html' % status_code, **ns)
      File "/usr/lib/python2.7/site-packages/notebook/base/handlers.py", line 466, in render_template
        template = self.get_template(name)
      File "/usr/lib/python2.7/site-packages/notebook/base/handlers.py", line 462, in get_template
        return self.settings['jinja2_env'].get_template(name)
    KeyError: 'jinja2_env'`

I'm not sure but this might be due to the implementation of [_check_kernel_id](https://github.com/jupyter/notebook/blob/master/notebook/services/kernels/kernelmanager.py#L386) on **MappingKernelManager**. This tries to render the output using the template which is not existent. Maybe this has to do something with [this issue](https://github.com/jupyter/kernel_gateway/issues/71)?

Any help with this?

**Comment by parewa-aswin** [comment]
Yeah, I did feel it wasn't due to EG as my searches led me to the issue on Kernel Gateway as well and the stack trace somewhat pointed to the same.

I've my own application issuing the request using the jupyterlab/services KernelManager, so most probably it's with KG as you say. I'll open an issue there then.

Thanks. You can close the issue here.

**Comment by kevin-bates** [comment]
I suppose this could be an edge case not handled by JKG and NB2KG if that endpoint request is relatively new.

Can you elaborate a bit on what you mean by?
>I've my own application issuing the request using the jupyterlab/services KernelManager

What I meant by "own application" is that your application is responsible for issuing the code.  This sounds more like you're using jupyterlab as your notebook server -which, with NB2KG, should have parity with Notebook behavior.

**Comment by parewa-aswin** [comment]
What I mean by 'own application' is I've my own non-notebook web client (a code editor) which uses jupyterlab services to connect to the API endpoints for execution of my code on EG's kernels, like [this example](https://github.com/jupyterlab/jupyterlab/tree/master/packages/services/examples/browser-require).

The only reason I use jupyterlab/services is that, it provides classes and wrappers to communicate with the endpoints, that's it.

**Comment by kevin-bates** [comment]
Thank you.  I wasn't aware of such services.
