### ISSUE TITLE
Remove Python 2.x support on EG 2.0.0 release

### ISSUE THREAD

**Issue by lresende** [jupyter/enterprise_gateway#573]
Various other Jupyter projects are only supporting Python 3.5 and above, and Enterprise Gateway should also move to that direction.

**Comment by kevin-bates** [comment]
It will also be nice to remove the flakey python 3.4 from travis.  When doing so, we should see how 3.7 works (it wasn't quite ready 6 months ago or so) and should probably add python 3.5, leaving us with 3.5, 3.6 and 3.7(?).

**Comment by lresende** [comment]
@kevin-bates Yes to all !!!

**Comment by lresende** [comment]
And another support for going into this direction: https://python3statement.org/
