### ISSUE TITLE
Errors(timeout and WebSocket handshake error) when deploying enterprise gateway in yarn clusters

### ISSUE THREAD

**Issue by jrcblue** [jupyter/enterprise_gateway#597]
Hello!
We attempted to deploy the gateway to a cluster with yarn, and we configured the environment, NB2KG and configurations following the doc. The problem is that when we start notebook and enterprise gateway, there is something wrong with the connection to kernel. Enterprise gateway indicates a error of timeout and in the webpage of  jupyter notebook, console indicates a error:

WebSocket connection to 'ws://10.239.47.211:12345/api/kernels/efaa060e-bbaa-4122-95d2-b769c2755b5c/channels?session_id=ceb7d42441154ed895ad6c9cc204c3ba' failed: Error during WebSocket handshake: Unexpected response code: 200

and in shell, notebook throws an error: 
/root/miniconda3/envs/jeg/lib/python3.6/site-packages/nb2kg/handlers.py:87: RuntimeWarning: coroutine 'WebSocketHandler.get' was never awaited 

I suppose these errors suggest there is something wrong with Websocket, but a notebook without NG2KG can run normally.

I would appreciate it if you have any solution or idea about this.

**Comment by kevin-bates** [comment]
Fixed in the 0.6.0 version of [NB2KG](https://pypi.org/project/nb2kg/).
