### ISSUE TITLE
KERNEL_WORKING_DIR in case of spark-yarn cluster mode

### ISSUE THREAD

**Issue by Gsbreddy** [jupyter/enterprise_gateway#618]
Hi,
There is an env KERNEL_WORKING_DIR for setting kernel dir for containers. What about the yarn containers? Because when I launch kernel using spark python cluster mode and do a `pwd` i get some random location inside container. But I want the working dir as my home folder. Is this possible as of now, maybe by using some env?

**Comment by kevin-bates** [comment]
Correct.  `KERNEL_WORKING_DIR` only gets applied in docker container configurations (including Kubernetes).  There may be some way to configure YARN to honor such a setting (assuming the underlying "working dir" exists - which is also the case with docker containers) but I'm not aware of that.

**Comment by Gsbreddy** [comment]
I think one way is to add script in startup folder of ipython so that we will get current directory. But I am not sure if this is the only way.
