### ISSUE TITLE
Refactor KernelSessionManager to allow for different forms of persistence

### ISSUE THREAD

**Issue by kevin-bates** [jupyter/enterprise_gateway#644]
The current `KernelSessionManager` does a decent job of isolating it's persistence methods, but we should convert those methods into abstract methods and create a subclass `FileKernelSessionManager` to hold the file-based persistence implementations.

This will more easily enable others to bring their own forms of persistence (namely NoSQL or KV stores).

**Comment by Gsbreddy** [comment]
Hi kevin, we actually developed file based persistence and using it currently with two EG and writing kernel files to a nfs based location. Once we are good with everything and all test cases we will be able to contribute back. Thanks.
