### ISSUE TITLE
Explore the ability to support dynamic configurations

### ISSUE THREAD

**Issue by kevin-bates** [jupyter/enterprise_gateway#647]
**Use case:** As an admin or dev ops engineer, I need the ability to change configuration parameters without restarting Enterprise Gateway.

Because Enterprise Gateway is a true multi-tenant environment, potentially hosting hundreds of users, it would be good to provide the ability to change configuration options without having to restart Enterprise Gateway.

Examples include adjusting the remote-hosts used by the DistributedProcessProxy, updating the unauthorized-users list, adjusting the culling timeout value, adding a kernel to the whitelist, etc.

From [this comment](https://github.com/jupyter/enterprise_gateway/pull/641#issuecomment-486463905):
>Via a debugger I found that if I load the configuration after startup (and after making a change), I see the updated value reflected in the member (traitlet) variable. This implies that you could have a PeriodicCallback that simply refreshes the configuration (although this is another case where 'watching' is better). So things like remote-hosts, authorized-users, or whitelists could (in theory) be updated without having to restart EG.

**Comment by SolarisYan** [comment]
That's a practical feature

**Comment by kevin-bates** [comment]
I have an implementation ready.  I think I'd like to wait a couple days to see how [traitlets PR 521](https://github.com/ipython/traitlets/pull/521) unfolds.  If it may take awhile for a release to occur, we can use temporary code that resides in EG.

**Comment by kevin-bates** [comment]
Update: We should be able to move forward with more "client-side" code once https://github.com/ipython/traitlets/pull/522 is available in a release.  This PR enables the ability to reload configuration files and, although not as fully baked in as we'd like (see https://github.com/ipython/traitlets/pull/521), we can have that "driver code" in the application itself.
