### ISSUE TITLE
Does viewing and editing a notebook require a kernel be started

### ISSUE THREAD

**Issue by thincal** [jupyter/enterprise_gateway#650]
My requirement is that notebook viewing and editing won't start a kernel until running the notebook, is this possible for the jupyter enterprise gateway design ?

**Comment by kevin-bates** [comment]
Enterprise Gateway is a headless server that handles requests to manage a kernel's life-cycle.  As a result, this kind of thing is outside EG's scope and is something that the client portions Notebook/Lab or whatever front end is talking to EG needs to handle.  Once the user decides to then run the notebook, the /api/kernels REST api would then be invoked and EG would do its thing.

I've seen your additional comment on the open Notebook issue and agree that would be a nice thing - but isn't something EG would provide.
