### ISSUE TITLE
Fixup docs relative to releases and links

### ISSUE THREAD

**Issue by kevin-bates** [jupyter/enterprise_gateway#652]
This forum post uncovered a number of issues relative to our documentation and its links to resources: https://discourse.jupyter.org/t/jupyter-enterprise-gateway-kernel-configuration-download-link-not-working-error-404-not-found/911

It's unfortunate that the `latest` is the default since we produce references to non-existent files (by default)!  
Is there a way to change the default version?  If so, then how would someone see the `latest` docs?  Not sure the best approach here.  Or could the latest content reference the last released resources?  However, there would be times where you don't want to do that since that's misleading as well.  Perhaps folks just need to know that `latest` means `dev` and `dev` resources are not available for downloads. 

Using the version pulldown...
![image](https://user-images.githubusercontent.com/22599560/57147162-cd0b8500-6d7b-11e9-8da7-1d6782c1bea7.png)
there are several issues.

1. There is no `v2.0.0rc1` version of the docs.
2. The `v2.0.0-beta.1` reference produces `404`.
3. There is no `v1.1.1` version of the docs.

**Comment by lresende** [comment]
For now, I have resolved the missing releases:

![image](https://user-images.githubusercontent.com/382917/57157627-1bc61880-6d96-11e9-9a61-bf07d2d7f790.png)

As a reference for the future, when a release is out, there is a need to go to readthedocs->admin->versions and make the new release version public and save at the bottom.

**Comment by lresende** [comment]
I have moved the described style issues to [another](#653) issue, as it is a more complicated issue to resolve.

**Comment by kevin-bates** [comment]
Thank you @lresende!  What should we do about the `latest` version of the docs reference `dev` links that don't exist?
