### ISSUE TITLE
Fix/Enhance documentation style

### ISSUE THREAD

**Issue by lresende** [jupyter/enterprise_gateway#653]
From a stylistic point of view, the new theme - although it's in line with other Jupyter projects - does not produce a helpful left-hand pane for navigation. This is because our section names are too long for that format. As a result, I can't distinguish one section from another.

image
![image](https://user-images.githubusercontent.com/382917/57157905-cc341c80-6d96-11e9-9efe-aa97d8b39d8e.png)

vs.
image
![image](https://user-images.githubusercontent.com/382917/57157919-d0603a00-6d96-11e9-8d81-5d1d47796c2b.png)

I think we need to look into using shorter section names so that there isn't as much wrapping going on - or find a slightly different theme or format.

**Comment by kevin-bates** [comment]
I think @echarles' work on #677 and #680 address the primary issue here.  Closing.
