### ISSUE TITLE
Separate config for culling idle and busy kernels

### ISSUE THREAD

**Issue by amangarg96** [jupyter/enterprise_gateway#665]
Currently, there is only a single timeout configuration `--MappingKernelManager.cull_idle_timeout` with a Boolean option for `--MappingKernelManager.cull_busy`. 

I feel that it would be better to have a separate `--MappingKernelManager.cull_busy_timeout`. 

Idle timeout could be set to a short duration (say 10 minutes) so that inactivity from the notebook user leads to a timeout, and busy timeouts could be set to longer duration (say 6 hrs) to cull kernels for code executions (like training of a model) taking a very long time.

**Comment by kevin-bates** [comment]
@amangarg96 - This should be opened in the notebook project, as the implementation for culling is completely implemented in the MappingKernelManager.

I think there's some merit to this.  Currently, the options that influence culling (aside from the interval at which its checked) are: `cull_idle_timeout` (the number of seconds of inactivity - indpendnent of actual status), `cull_busy` (can kernels that are currently busy be culled?) and `cull_connected` (can the kernel be culled if there's a connected client?).

It seems like you could _implement_ your busy scenario by setting `cull_idle_timeout` to 6 hours with `cull_busy` and `cull_connected` = `True`.  However, you'd like the ability to **also** cull purely idle kernels after a different (shorter) amount of time.  For that scenario, you'd want a separate timeout and, likely, `cull_connected = True`.

So it sounds like you're trying to address the long-running training model case where it eventually completes within the (new) `cull_busy_timeout` (which I would assume implies `cull_busy = True`), but then you don't want to have to wait that same time period for the now truly idle kernel to be culled.  Is that correct?

So, in line with your example, you'd set `cull_idle_timeout = 600`, `cull_busy = False`, `cull_connected = True`, and `cull_busy_timeout = 21600` (6 hours).  I guess this could mean that `cull_busy_timeout` would _replace_ `cull_busy` - correct?

Not sure if there would need to be two different `cull_connected` options - one for inactivity and one for busy.  Seems like if the user is connected when the busy-timeout expires, the kernel should probably not get culled, I don't know.  Seems like things could get a little confusing unless this is also split out.

Besides tracking the `last_activity`, this would require that a boolean be added that indicates if the `last_activity` was a `busy` state.

Are these thoughts in line with yours?

**Comment by amangarg96** [comment]
I had seen [this](https://github.com/jupyter/notebook/pull/2215) PR earlier and I remembered that you worked on culling kernels, but I hadn't realised that it was contributed on Notebooks and not JEG.

Yes, these thoughts are exactly in line with my thoughts. 
And the long-running training model is exactly the kind of case I wanted to address. 

The [sessions API](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/jupyter/notebook/master/notebook/services/api/api.yaml#/sessions/get_api_sessions__session_) already tracks the `execution_state` of the kernel along with the `last_activity`, so maybe the busy-timeout can be tracked using that?

**Comment by kevin-bates** [comment]
I'd prefer that use of the sessions API be avoided since it isn't really used on the gateways.  However, I believe the necessary execution state could be captured [when the last activity is captured](https://github.com/jupyter/notebook/blob/master/notebook/services/kernels/kernelmanager.py#L408-L420).

**Comment by kevin-bates** [comment]
Closing - Any changes in this area are required in Notebook Server.
