### ISSUE TITLE
Kernel logos are not loading

### ISSUE THREAD

**Issue by RajeshHegde** [jupyter/enterprise_gateway#669]
After connecting to the enterprise gateway using nb2kg, kernels logos are throwing 404.

```
[D 2019-05-15 20:54:47.057 EnterpriseGatewayApp] Found kernel python2 in /usr/local/share/jupyter/kernels
[I 190515 20:54:47 web:2162] 200 GET /api/kernelspecs (127.0.0.1) 4.93ms
[D 2019-05-15 20:54:48.147 EnterpriseGatewayApp] Serving kernel resource from:
[W 190515 20:54:48 web:2162] 404 GET /kernelspecs/python3/logo-64x64.png (127.0.0.1) 2.93ms
[D 2019-05-15 20:54:48.154 EnterpriseGatewayApp] Serving kernel resource from:
[W 190515 20:54:48 web:2162] 404 GET /kernelspecs/python2/logo-64x64.png (127.0.0.1) 2.83ms
```

What could be the possible reason for this?

**Comment by kevin-bates** [comment]
Are you using Jupyter **Kernel** Gateway `2.2.0` or newer, or if in a container environment, the latest elyra/enterprise-gateway:dev image?  The particular change requires that both [JKG](https://github.com/jupyter/kernel_gateway/pull/314) and NB2KG be updated, and by the looks of your log statements, it looks like the NB2KG side of things is current.

**Comment by kevin-bates** [comment]
@RajeshHegde - any update?

**Comment by RajeshHegde** [comment]
@kevin-bates 
I'm was using Jupyter Enterprise Gateway 1.2.0 and nb2kg 0.6.0.

**Comment by kevin-bates** [comment]
EG uses kernel gateway for its handlers. Please ensure JKG is >= 2.2.0.

**Comment by RajeshHegde** [comment]
@kevin-bates 
Thanks. will upgrade the versions.
