### ISSUE TITLE
Kernels get orphaned when EG pod is stopped

### ISSUE THREAD

**Issue by michzimny** [jupyter/enterprise_gateway#672]
I'm opening this for the issue we started with @kevin-bates by the way in #671.

The issue is: the shutdown of the EG pod orhpans kernel pods in 100% cases. The kernel pods (and namespaces) still live, after the EG pod is stopped. If a new EG pod is started, it's not aware of the kernel pods.

The expected behaviour is that k8s sends `SIGTERM` to the EG pod that then reacts and iterates over the kernel pods to shut them down OR kernel session is persisted so the newly-created EG pod knows about the old kernels.

@kevin-bates's quotes from the other thread:

> Yes, I reproduced the orphaned kernel issue. We typically don't shutdown EG - at least until all kernels have been shutdown themselves. To "shutdown" EG in k8s, what are you doing? Are you stopping the service? deleting the deployment? When I reproduced the issue, I deleted the service.

> Ok. I've tried spending a bit more time with this tonight. Actually, deleting the service is not sufficient since I can just restart the service and the kernel is still usable. However, when I delete the EG pod, another is started, but it doesn't know about the running kernel(s) - which makes sense. I think we could address this by enabling kernel session persistence, but first, we should understand why the appropriate shutdown protocol is not evident in the pod. According to the docs, [`SIGTERM` should be sent to the EG during the 30 second grace period](https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods) when deleting the pod and [EG's built-in signal handler should cycle through and attempt to shutdown the kernels](https://github.com/jupyter/enterprise_gateway/blob/master/enterprise_gateway/enterprisegatewayapp.py#L293).

**Comment by michzimny** [comment]
> We typically don't shutdown EG - at least until all kernels have been shutdown themselves. To "shutdown" EG in k8s, what are you doing?

I use [that k8s object definition](https://github.com/jupyter/enterprise_gateway/blob/master/etc/kubernetes/enterprise-gateway.yaml) and apply it by `kubectl apply -f enterprise-gateway.yaml`. Then, I make changes to the yaml file, adjusting configuration etc., and call `kubectl apply ...` again. It ends up in recreation of the deployment, so the old pod gets destroyed.

(Actually, I use OKD (Openshift), not bare k8s, but I hope it's not relevant here.)

> I think we could address this by enabling kernel session persistence

@kevin-bates, I would rather stay with iterating and shutting down the kernels as the default signal handler (as it is supposed be implemented now according to the sources you referenced). In the signal handler, you don't know if one is just recreating the pod or shutting the EG instance completely (when one wants to drop EG completely, e.g. during tests). In the latter case, one would like not to stay with a mess (i.e. orphaned kernels) in the cluster. I assume that the signal handler is the only tool to track and shut down the kernel (apart from manually looking for the kernel namespaces/pods).

**Comment by michzimny** [comment]
Just a note: deleting the pod should result in [that log message](https://github.com/jupyter/enterprise_gateway/blob/master/enterprise_gateway/enterprisegatewayapp.py#L314). I cannot see it, so it seems that the signal is not handled as expected.

The entrypoint of the EG container is [bootstrap-enterprise-gateway.sh](https://github.com/jupyter/enterprise_gateway/blob/master/etc/docker/enterprise-gateway/bootstrap-enterprise-gateway.sh) and [start-enterprise-gateway.sh](https://github.com/jupyter/enterprise_gateway/blob/master/etc/docker/enterprise-gateway/start-enterprise-gateway.sh). I'm not a Bash expert but they probably do not properly propagate signals to the python process, so it's not aware of any signals sent to the container. Should we implement, in those Bash scripts, something [like this](http://veithen.io/2014/11/16/sigterm-propagation.html)?

By the way, by default, all deletes in k8s are graceful within 30 seconds. I wonder whether it's enough time to stop multiple kernel pods and delete its namespaces.

**Comment by kevin-bates** [comment]
Yes - I see the same thing (missing log entry).  The handling of `SIGTERM` works fine when running in a file system.  However, one of my colleagues noticed our container process was running as PID 1, which inhibits signal propagation.  We will need to use an init process (like `tini`) for the EG image.  I suspect the `SIGTERM` will flow after doing that.

Regarding the grace period, I suspect we should be okay with a 30 second window.  We can see how things go once we solve the signal propagation issue.

As for restart vs delete, we need to better understand how that works.  I think much of that could be resolved with a fully implemented HA solution.  I think the process would be to increase the replicas, but, yes, I agree, if the ultimate way these pods are shutdown is via the `SIGTERM` approach, then we'll have an issue.   Let's deal with the immediate issue first, then lump this other issue into the topic of HA and devOps kinds of things - if you're ok with that.

**Comment by michzimny** [comment]
Regarding PID 1, I'm not sure I understand. For me, in the EG container, bootstrap-enterprise-gateway.sh is PID 1. Then, start-enterprise-gateway.sh and the python process get higher PIDs. So, we probably need to add `exec` or `trap` commands to the both Bash scripts, as in the article I referenced.

Re. restart vs delete, yeah, I'm ok.

**Comment by kevin-bates** [comment]
I didn't look that closely, but I think we're on the same page - especially since I see the handler shutting down kernels outside of the container env.  If you want to spend time on this, that would be great.  Otherwise, I'll try to get to this early next week as I'm traveling at the moment, then traveling again later next week.

**Comment by michzimny** [comment]
I might find some time next week. I will write first here, so we could synchronise not to work in parallel on the same fix.

**Comment by kevin-bates** [comment]
@michzimny - I found some cycles and submitted a fix.  Seemed to be a combination of the lack of an init process and bash getting in the way (missing exec has you surmised).  I found [this page](https://kkc.github.io/2018/06/06/gracefully-shutdown-docker-container/) helpful as well.

Thank you for raising this issue.  It would be great if you could take the image I posted for a spin!
