### ISSUE TITLE
how to add python package for kubernets configurations ?

### ISSUE THREAD

**Issue by jayendra13** [jupyter/enterprise_gateway#693]
## Description
Currently, I am using enterprise_gateway with kubernets, it is working well how can I install python packages so when I deploy the same config on a new k8s cluster I get those python packages preloaded?

**Comment by kevin-bates** [comment]
Welcome to EG!  For persistent deployments, you'd want to [extend the appropriate kernel image with the desired packages](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/docker.html#extending-existing-kernel-images).

**Comment by jayendra13** [comment]
Thanks Got it!
