### ISSUE TITLE
Yarn application's FAILED state is not handled

### ISSUE THREAD

**Issue by nareshsankapelly** [jupyter/enterprise_gateway#708]
Kernel launch request is submitted to Yarn and it failed due to some packages missing (Yarn App's state is FAILED). For some reason, FAILED state is not handled in JEG.  I see the following code. 
```
class YarnClusterProcessProxy(RemoteProcessProxy):
    initial_states = {'NEW', 'SUBMITTED', 'ACCEPTED', 'RUNNING'}
    final_states = {'FINISHED', 'KILLED'}  # Don't include FAILED state 
```
What is the rationale behind not including FAILED state in final states? 

## Environment
- Enterprise Gateway Version: 1.2.0
- Platform: Spark on Yarn (Cluster Mode)

**Comment by kevin-bates** [comment]
Hi @nareshsankapelly - thank you for raising this issue!  Short answer: I have no idea why FAILED state isn't included in the final states.  Here's the [commit](https://github.com/jupyter/enterprise_gateway/pull/16/commits/6f85a0a4b64cae9bb876cfd35867960702957a86).  Unfortunately, (and surprisingly) I didn't add any insight into why that's the case other than leaving the explicit comment.

I'm wondering if we thought it was some kind of edge case or something and probably had a local (in office) discussion that is quite unhelpful at this point.

However, based on nearly two years of usage and reviewing the use of `final_states`, I'd be comfortable adding it into the set - as it makes a lot of sense.  I suspect FAILED states are quite infrequent (although I ran into a case of this other day on a shutdown scenario) so its absence from the set hasn't really interfered with things.

Would you be willing to contribute this change?

**Comment by nareshsankapelly** [comment]
Sure. I will make this change.
