### ISSUE TITLE
need info on supporting scala 2.12 version for toree launcher and toree assembly

### ISSUE THREAD

**Issue by suryag10** [jupyter/enterprise_gateway#768]
hi,
we are using spark 2.4.2 which is having scala as 2.12.8, when we tried to bring up the scala kernel, we see the incompatability  with the spark jars(2.12.8) and toree jars(2.11.12) and scala kernel fails to comeup. Is there a way we can compile toree jars for scala 2.12.8 or do we need to rewrite the code for the same? Pls let us know.

**Comment by lresende** [comment]
For some reason, Spark 2.4.2 is the only one that have Scala 2.12 as default, please move to Spark 2.4.3 which should solve the Scala version problem. Having said that, we are working on a new toree release that should bring better support for Scala 2.12

**Comment by suryag10** [comment]
thx Luciano

**Comment by suryag10** [comment]
Can i know what is the expected date for the upgrade to scala 2.12?
