### ISSUE TITLE
need info on configuring the ssl at nb2kg

### ISSUE THREAD

**Issue by suryag10** [jupyter/enterprise_gateway#769]
hi
we are trying to use the ssl at EG and are facing the issues while configuring the ssl at the nb2kg. Can we have a sample example which illustrates the same Note that the ssl from KIP is working.

Surya

**Comment by lresende** [comment]
I believe NB2KG is reusing the same config is the gateway:
https://github.com/jupyter/nb2kg/blob/2c27c3ee4d763604d75148648edcf701a604a250/nb2kg/handlers.py#L33.

**Comment by suryag10** [comment]
thx. I found the way to configure, its working.

**Comment by kevin-bates** [comment]
Fantastic.  If the information differs from [what we post in our docs](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/getting-started-security.html#using-ssl-for-encrypted-communication) - or you found anything helpful that is not documented, it would be ideal if you could provide some updates.

**Comment by suryag10** [comment]
> Fantastic. If the information differs from [what we post in our docs](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/getting-started-security.html#using-ssl-for-encrypted-communication) - or you found anything helpful that is not documented, it would be ideal if you could provide some updates.

Hi Kevin,
Few points to note with the above comment. I feel following should be added:
1. Document the ssl related environment variables KG_KEYFILE, KG_CERTFILE for EG.
2. Document the environment variable VALIDATE_KG_CERT for nb2kg
3. provide the documentation for the SSL config params for the KIP as well.

**Comment by suryag10** [comment]
for item 3, i had raised a INFO issue https://github.com/jupyter/enterprise_gateway/issues/772

**Comment by kevin-bates** [comment]
A PR would be great.  Please note that as of Notebook 6.x, NB2KG is no longer required since it is built directly into Notebook.  As a result, the supported parameters and env names have been changed, so any doc updates should probably provide both sets of names and/or parameters (since the builtin approach typically works from a configuration file rather than envs).
