### ISSUE TITLE
Support for grid engine

### ISSUE THREAD

**Issue by pkvprakash** [jupyter/enterprise_gateway#782]
Is there any plan to have support for running kernels remotely through grid engine?

https://en.wikipedia.org/wiki/Oracle_Grid_Engine
http://www.univa.com/products/

**Comment by kevin-bates** [comment]
Hi @pkvprakash - thanks for the question.

Short answer: No.  That said, there's nothing to preclude anyone looking into building a [ProcessProxy](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/system-architecture.html#process-proxy) relative to grid engine.  However, given I don't have access to such a cluster, it would be difficult fully support such a capability.

In looking into this briefly, it looks like there's a python api.  The basic functionality needed to build a process proxy is the ability to:
1. launch a process or container
1. discover the the launched entity and determine the host on which it was scheduled
1. communicate to the entity via zmq sockets and a regular unix socket
1. shutdown the launched entity

If those kinds of things are present, implementing a process proxy for grid engine is possible.  

Should you choose to implement `GridProcessProxy`, I will be happy to help guide the implementation and integration efforts.

**Comment by pkvprakash** [comment]
@kevin-bates Thank you for the answer. 
 
> In looking into this briefly, it looks like there's a python api

You are correct. There are python APIs that can be used to interact with grid.

> The basic functionality needed to build a process proxy is the ability to:
>   1. launch a process or container
>   2. discover the the launched entity and determine the host on which it was scheduled
>   3. communicate to the entity via zmq sockets and a regular unix socket
>   4. shutdown the launched entity
> If those kinds of things are present, implementing a process proxy for grid engine is possible.

Yes. All the four points are achievable using the APIs.

> Should you choose to implement GridProcessProxy

I will be happy to implement `GridProcessProxy`

**Comment by kevin-bates** [comment]
Closing as this is probably not going to happen.  We can reopen down the road.

@pkvprakash  - If this has not yet been developed, but you are still interested, I would suggest created a [_kernel provisioner_](https://jupyter-client.readthedocs.io/en/latest/provisioning.html) instead, since the rest of the juptyer framework is using that model and EG will move there in its 4.0 release (kernel provisioners and process proxies are incompatible).
