### ISSUE TITLE
Why is /opt/workspace path not recognized?

### ISSUE THREAD

**Issue by MilenkoM** [jupyter/enterprise_gateway#841]
Help us improve the Jupyter Enterprise Gateway project by reporting issues
or asking questions. 

## Description
I am running my code(need both Python and PySpark) in my JupyterLab. My code:

> import boto3
> import os
> from pyspark.sql import SparkSession
> 
> spark = SparkSession.builder.appName('Test').getOrCreate()
> def get_matching_s3_objects(bucket, prefix="", suffix=""):
> 
>     s3 = boto3.client("s3")
>     paginator = s3.get_paginator("list_objects_v2")
> 
>     kwargs = {'Bucket': bucket}
>     if isinstance(prefix, str):
>         prefixes = (prefix, )
>     else:
>         prefixes = prefix
> 
>     for key_prefix in prefixes:
>         kwargs["Prefix"] = key_prefix
> 
>         for page in paginator.paginate(**kwargs):
>             try:
>                 contents = page["Contents"]
>             except KeyError:
>                 break
> 
>             for obj in contents:
>                 key = obj["Key"]
>                 if key.endswith(suffix):
>                     yield obj
> 
> def get_matching_s3_keys(bucket, prefix="", suffix=""):
> 
>     for obj in get_matching_s3_objects(bucket, prefix, suffix):
>         yield obj["Key"]
> 
> new_list =[]        
> for k in get_matching_s3_keys(bucket='cw-milenko-tests', prefix='Json_gzips/ticr_calculated_2', suffix='.gz'):
>     new_list.append(k)
>     
> 
> dfs = [spark.read.json(file) for file in new_list]
> 
> print (map(lambda df: len(df.schema), dfs))
> 

## Screenshots / Logs

`AnalysisException: Path does not exist: file:/opt/workspace/Json_gzips/ticr_calculated_2_2020-05-27T00-01-21.json.gz;`

Anyway pwd shows
`'/opt/workspace'`

## Environment
 I used this 
`(https://github.com/andre-marcos-perez/spark-cluster-on-docker) to run my spark cluster`
- Enterprise Gateway Version [e.g. 1.x, 2.x, ...]
- Platform: [e.g. YARN, Kubernetes ...]
- Others [e.g. Jupyter Server 5.7, JupyterHub 1.0, etc]

Jupyterlab 2.1.4

**Comment by kevin-bates** [comment]
Hi @MilenkoM - I don't see any relation to Enterprise Gateway from this description or in the [spark-cluster-on-docker](https://github.com/andre-marcos-perez/spark-cluster-on-docker) github repository.  If Enterprise Gateway is configured for use in this particular configuration, could you please provide the `kernel.json` file corresponding to the kernel you're experiencing these issues with?

**Comment by kevin-bates** [comment]
Closing due to lack of response and information.
