### ISSUE TITLE
Add typing hints to kernelspec handler

### ISSUE THREAD

**Issue by kevin-bates** [jupyter/enterprise_gateway#849]
Part of the larger [umbrella issue](https://github.com/jupyter/enterprise_gateway/issues/847) this issue will track adding typing hints to the kernelspecs handlers located in `enterprise_gateway/services/kernelspecs`.

**Comment by uniocto** [comment]
I tried to work on it, but I got an error in ittest.
How can I deal with this?
```
$ make itest
make itest-docker-prep
Error: No such service: itest-docker
make[1]: [itest-docker-prep] Error 1 (ignored)
# Check if swarm mode is active, if not attempt to create the swarm
Starting enterprise-gateway swarm service (run `docker service logs itest-docker` to see service log)...
/bin/bash: etc/docker/enterprise-gateway-swarm.sh: No such file or directory
make[1]: *** [itest-docker-prep] Error 127
make: *** [itest-docker] Error 2
```

When this ittest issue is resolved, I want to send you a pull request  and would appreciate your guidance.

**Comment by kevin-bates** [comment]
Hi @uniocto - sorry about this.  This target needs some work and should not impact anything related to type hints. It is not performed during CI either.  I'm looking into this right now.

The CI tests are `make test` and `make itest-yarn`.  I think `make test` success is sufficient.
