### ISSUE TITLE
options to disable restart of kernels 

### ISSUE THREAD

**Issue by jinpenglv** [jupyter/enterprise_gateway#854]
## Description
When kernels crash, jupyter tries to be helpful and "auto restarts" the kernel. This operation usually fails and leaves the user in a confusing state of an unusable kernel and no way to look into the errors that caused the original kernel to crash. 

There are two options that are supposed to work here: `KernelManager.autorestartBool=False` and `KernelRestarter.restart_limit = 0`, but Jupyter Enterprise Gateway seems to ignore both of them. 

## Screenshots / Logs
To reproduce it:

```
import pandas as pd
import numpy as np
n_rows = 1_000_000 # adjust this number to be more than your machine's memory but not too big to avoid the 'array too big' error
n_cols = 1_000_000 # adjust this number it works in my case
df = pd.DataFrame(np.random.randint(0, 100, size=(n_rows, n_cols)), columns=['col%d' % i for i in range(n_cols)])
df.head()
```

after running above, I got:
![Screen Shot 2020-08-18 at 11 39 28 AM](https://user-images.githubusercontent.com/69866531/90552502-cdce5300-e147-11ea-958b-5c7ddff0e515.png)

After a few seconds, the left corner becomes `autorestaring` forever:

![Screen Shot 2020-08-18 at 11 41 20 AM](https://user-images.githubusercontent.com/69866531/90552538-daeb4200-e147-11ea-8405-3517dd528aff.png)

## Environment

- Enterprise Gateway Version : 2.1.1
- Platform: Kubernetes
- Others: JupyterHub 1.1.0

**Comment by kevin-bates** [comment]
I'm not reproducing this.  How are you setting the properties on EG?

Here's a snapshot from the end of the `start-enterprise-gateway.sh` script that is invoked when the EG POD starts (the last options are relevant here):
```bash

exec jupyter enterprisegateway \
	--log-level=${EG_LOG_LEVEL} \
	--KernelSpecManager.whitelist=${EG_KERNEL_WHITELIST} \
	--RemoteMappingKernelManager.cull_idle_timeout=${EG_CULL_IDLE_TIMEOUT} \
	--RemoteMappingKernelManager.cull_interval=${EG_CULL_INTERVAL} \
	--RemoteMappingKernelManager.cull_connected=${EG_CULL_CONNECTED} \
	--RemoteMappingKernelManager.default_kernel_name=${EG_DEFAULT_KERNEL_NAME} \
	--KernelManager.autorestart=False \
	--KernelRestarter.restart_limit=0
```

Without these options, I can manually terminate a kernel POD and the kernel will restart.  With these changes, nothing happens after POD termination - the kernel (POD) stays terminated and EG thinks the kernel is still running until I issue a `DELETE` against the REST API to: `api/kernels/<kernel-id>`.  Once I terminate via REST, Lab's status switches to 'No Kernel!' until I restart or shutdown the kernel via Lab/Notebook.

I have pushed [`elyra/enterprise-gateway:854`](https://hub.docker.com/r/elyra/enterprise-gateway) to docker hub if you're interested.  Note that this is built on the 2.2.0rc2 image - which is configured to use the async kernel management.

**Comment by jinpenglv** [comment]
I agree. It works. It seems my eg did not pick my config somehow. Thanks so much for investigating.
