### ISSUE TITLE
Support custom certificate truststores for EG dispatch to SSL Enabled Yarn

### ISSUE THREAD

**Issue by akshaykjain** [jupyter/enterprise_gateway#887]
## Description
yarn-api-client Resource Manager consumes a `verify` [flag](https://github.com/CODAIT/hadoop-yarn-api-python-client/blob/d61085cff2aedf0843645fa08439c3ab5731b748/yarn_api_client/resource_manager.py#L70-L72) that processes boolean values to verify the server's TLS certificate or a string that should be a path to a CA bundle to be used. There should be a way to support custom certificate truststore from enterprise_gateway for dispatch to SSL enabled Yarn.

## Logs
status in jeg.log on running a Jupyter Notebook with custom cacerts not passed to Yarn RM:
```
[W 2020-09-24 15:36:52.281 EnterpriseGatewayApp] Query for kernel ID '50ab1833-65dc-463a-a6c8-7873e5386d18'
failed with exception: <class 'requests.exceptions.SSLError'> - 'HTTPSConnectionPool(host='cdhv632-master.fyre.ibm.com',
port=8090): Max retries exceeded with url: /ws/v1/cluster/apps?startedTimeBegin=1600986995000 (Caused by
SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))'.
```
Kernel failed to start:
![image](https://user-images.githubusercontent.com/35847840/94207482-54174b00-fee5-11ea-8361-7371acac9202.png)

## Environment
- Enterprise Gateway Version 2.1
- Platform: CDH 6.0.1 with TLS enabled
- Others: [Truststores](https://docs.cloudera.com/documentation/enterprise/6/6.3/topics/auto_tls.html#auto_tls_agent_files) available for use

**Comment by akshaykjain** [comment]
Potential Fix https://github.com/jupyter/enterprise_gateway/pull/888

**Comment by kevin-bates** [comment]
Excellent - thank you @akshaykjain!

**Comment by kevin-bates** [comment]
Closed via https://github.com/jupyter/enterprise_gateway/pull/888
