### ISSUE TITLE
Bad request error while connecting jupyterhub to enterprise gateway

### ISSUE THREAD

**Issue by abinassahoo** [jupyter/enterprise_gateway#902]
## Description
Hi Team,
I am following this [doc](https://blog.jupyter.org/on-demand-notebooks-with-jupyterhub-jupyter-enterprise-gateway-and-kubernetes-e8e423695cbf) to integrate my jupyterhub with enterprise gateway. But I am getting below error while launching a notebook user from jupyterhub. It would be great if you can help here.

Command used to deploy jupyterhub:
helm upgrade --install --force hub jupyterhub/jupyterhub --namespace hub --version 0.7.0 --values config.yaml

## Screenshots / Logs
Spawn failed: (400) Reason: error HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Wed, 11 Nov 2020 11:10:36 GMT', 'Content-Length': '504'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod in version \"v1\" cannot be handled as a Pod: v1.Pod.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects \" or n, but found 6, error found in #10 byte of ...|\"value\": 60}, {\"name|..., bigger context ...|buser\"}, {\"name\": \"KG_REQUEST_TIMEOUT\", \"value\": 60}, {\"name\": \"KG_URL\", \"value\": \"http://k8s-mst101|...","reason":"BadRequest","code":400}

![image](https://user-images.githubusercontent.com/18737307/98804891-cc59b180-243c-11eb-9ee4-e3538cce51e7.png)

## Environment

- Enterprise Gateway Version 2.3.0.dev1
- Platform: K8s
- Others : Jupyterhub 0.7.0

My config.yaml looks like below
================
hub:
  db:
    type: sqlite-memory
  extraConfig: |-
    config = '/etc/jupyter/jupyter_notebook_config.py'
    c.Spawner.cmd = ['jupyter-labhub']
proxy:
  secretToken: "XXXX"
ingress:
  enabled: false
  hosts:
    - ""
singleuser:
  defaultUrl: "/lab"
  image:
    name: elyra/nb2kg
    tag: dev
  storage:
    dynamic:
      storageClass: nfs-dynamic
  extraEnv:
    KG_URL: <<GATEWAY_URL>>
    KG_HTTP_USER: nbuser
    KG_HTTP_PASS: datalab
    VALIDATE_KG_CERT: false
    KERNEL_WORKING_DIR: /gfs/nbuser
    KERNEL_USERNAME: nbuser
    KG_REQUEST_TIMEOUT: 60
prePuller:
  hook:
    enabled: false
rbac:
  enabled: true
debug:
  enabled: true

**Comment by kevin-bates** [comment]
Hello again - looks like you're giving Kubernetes a shot. :smile:

I see you're still using `elyra/nb2kg` along with the older envs (`KG_`).  As noted on #901, you should be using a notebook image based on Notebook >= 6.0.  An image used by the [Elyra](https://github.com/elyra-ai/elyra) project to launch instances of Jupyter Lab is [`jupyterhub/k8s-singleuser-sample:0.9.0`](https://github.com/elyra-ai/elyra/blob/master/etc/docker/elyra/Dockerfile#L19).  In fact, this image is essentially "ready" to run against an EG server based on its [startup script](https://github.com/elyra-ai/elyra/blob/master/etc/docker/elyra/start-elyra.sh).  If you wanted to just deploy an Elyra server (which is Jupyter Lab running with a server extension that enables pipeline management) you could just reference this [documentation](https://elyra.readthedocs.io/en/latest/recipes/deploying-elyra-in-a-jupyterhub-environment.html). In fact, this documentation should be nearly identical to what you want to do.

I think you might want to break this task down into multiple steps:
1. Get hub working with launching notebook servers where the kernels run within the launched notebook server pod/container.  This will be completely based on the Hub documentation.  When reading those docs, keep your eyes out for how to adjust the configuration of the spawned notebook server - both in terms of conveying environment variables to the spawned instance, and for setting specific command-line options or specific configuration settings that affect the spawned instance.
2. Deploy an Enterprise Gateway server into the same managed k8s cluster.  You should be able to hit the deployed EG instance from outside the cluster using `jupyter notebook --gateway-url=<URL of the EG service/ingress>` and confirm that's working as expected.
3. Adjust the configuration for spawned notebook servers in hub to redirect their kernel requests to the EG server via `--gateway-url` or the `JUPYTER_GATEWAY_URL` env.

Once all 3 steps have been successfully completed, you'll have connected hub to EG (via a notebook server).

Good luck, please check back regarding your progress.  (Thanks)

**Comment by kevin-bates** [comment]
Closing due to lack of response.
