### ISSUE TITLE
Docker pull elyra/kernel-r:2.3.0 fails

### ISSUE THREAD

**Issue by ricklamers** [jupyter/enterprise_gateway#904]
## Description
Docker Hub pulls of elyra/kernel-r:2.3.0 fails

`docker pull elyra/kernel-r:2.3.0`

The error is:
error pulling image configuration: unknown blob

Looks like it's an open issue with Docker Hub: https://github.com/docker/hub-feedback/issues/2039

Reason I'm posting it here is because a new push might solve the issue for end users relying on Docker Hub.

Per Docker's @binman-docker "For affected images, re-pushing them should resolve the problem."

## Environment
- Enterprise Gateway Version: 2.3.0
- Platform: Docker
- Others: Docker 19.03.13, Ubuntu 20.04.01 LTS

**Comment by kevin-bates** [comment]
Hi Rick - sorry about that.  I've built and pushed elyra/kernel-r:2.3.0 and confirmed it could be pulled.

Here are the signature details from the push:
2.3.0: digest: sha256:dcbe495875532e808aedfb7e330d94ca9b850dff4225833ab8aff99445cebbb8 size: 5772

If you are successful with the pull, please go ahead and close this issue - thanks.

**Comment by ricklamers** [comment]
It works now! Thanks for pushing it.
