### ISSUE TITLE
Add tensorflow 2.x kernel to enterprise gateway launcher

### ISSUE THREAD

**Issue by dummys** [jupyter/enterprise_gateway#919]
Hi, please add support for tensorflow 2.x kernel to the launcher.

**Comment by lresende** [comment]
After some investigation, the current version of Tensorflow added into EG is `Tensorflow 2.2.0`. One thing is that we might want to update to the latest version `Tensorflow 2.4.0`, but do we also want to have a `Tensorflow 1.5.0` available?

**Comment by kevin-bates** [comment]
I'd prefer we stick to our current approach of trying to be "as current as possible" and not expand the support matrix with multiple releases.  We also emphasize that the images (and kernelspecs) are _examples_ and I think that's a good model.  That said, it looks like the tensorflow-gpu image is built on 1.12 and probably warrants an update (this image [looks interesting](https://hub.docker.com/layers/tensorflow/tensorflow/2.4.0-gpu-jupyter/images/sha256-75c2209354e67c1903468c499cd3b9d93f9eac93fc04ae811ea454f7406cc017?context=explore)).  

I'd also be in favor of moving to a more recent `jupyter/tensorflow-notebook` image with 2.4.0 as you discovered (which also happens to match our current image tags).  This appears to be the latest version: [jupyter/tensorflow-notebook:703d8b2dcb88](https://hub.docker.com/layers/jupyter/tensorflow-notebook/703d8b2dcb88/images/sha256-6f9a167d3b1e22d98d08fa7fcdb024604da317c6557937f6768dc71614a44d28?context=explore) to reference.

Thanks @lresende!

**Comment by dummys** [comment]
yeah thats a good idea. Please tell me when I can update please.

**Comment by lresende** [comment]
@dummys I have pushed updates to the images last night, please give it a try.

**Comment by dummys** [comment]
ok but what must I do ?
