### ISSUE TITLE
missing package in the latest release of jupyter-gateway for helm

### ISSUE THREAD

**Issue by dummys** [jupyter/enterprise_gateway#941]
Hi,

In the documentation you tell to install using helm:

```
the helm chart tarball is also accessible as an asset on our release page:
helm install --name enterprise-gateway --atomic --namespace enterprise-gateway https://github.com/jupyter/enterprise_gateway/releases/download/v2.5.0/jupyter_enterprise_gateway_helm-2.5.0.tgz
Configuration
```
The problem is that you forget to deploy the helm for 2.5.0 under release:
https://github.com/jupyter/enterprise_gateway/releases/tag/v2.5.0

**Comment by kevin-bates** [comment]
Sorry about this.  The drag/drop approach wasn't working and there appears to be a new upload files option (at least I don't recall this being there previously) that is allowing the uploads.  I had gotten distracted when this was first encountered and I appreciate the issue/gitter post as a reminder.  Thanks.
