### ISSUE TITLE
Image of enterprise-gateway with python3.8?

### ISSUE THREAD

**Issue by zexuan-zhou** [jupyter/enterprise_gateway#942]
Is there an enterprise-gateway that's built with python3.8? 

Thank you

**Comment by kevin-bates** [comment]
No, sorry - we only build against a single version of python which is derived from EG's base image - [jupyter/minimal-notebook:703d8b2dcb88](https://hub.docker.com/layers/jupyter/minimal-notebook/703d8b2dcb88/images/sha256-9cea750e610cf084be244e6c61c3b16506ef4acdc7e410cf8239959cdd89f16e?context=explore) which uses conda 4.9.2, whose default python is 3.7.6.

**Comment by zexuan-zhou** [comment]
> No, sorry - we only build against a single version of python which is derived from EG's base image - [jupyter/minimal-notebook:703d8b2dcb88](https://hub.docker.com/layers/jupyter/minimal-notebook/703d8b2dcb88/images/sha256-9cea750e610cf084be244e6c61c3b16506ef4acdc7e410cf8239959cdd89f16e?context=explore) which uses conda 4.9.2, whose default python is 3.7.6.

Thank you. I see. Is there any plan on supporting python3.8?

**Comment by kevin-bates** [comment]
EG runs against python 3.8 - it is supported.  We just don't deliver python-specific images.  Our [CI](https://github.com/jupyter/enterprise_gateway/actions/runs/593528672) runs against Python 3.6, 3.7, 3.8, and 3.9.
