### ISSUE TITLE
Usage of blacklist/whitelist terms

### ISSUE THREAD

**Issue by suryag10** [jupyter/enterprise_gateway#970]
I see that the terms whitelist is being used a lot in the enterprise-gateway. There has been discussion in the opensource community to use the alternative terms for the same. For example: https://news.ycombinator.com/item?id=23801134 , https://github.com/kubernetes/website/issues/6525. Is there any similar approach being taken here as well to change the terms?

**Comment by kevin-bates** [comment]
Hi @suryag10 - thank you for bringing this up.  Yes, this is something I've thought about for a while and has been discussed in this repository (see https://github.com/jupyter/enterprise_gateway/issues/957#issuecomment-828007679).  I'm not sure how @telamonian is coming along with things, but it's on our radar.   I've also proposed a similar change for the kernelspec.whitelist trait in [`jupyter_client`](https://github.com/jupyter/jupyter_client/issues/642).  

As you might imagine, navigating configuration property name changes can be a bit disruptive, so its not always straightforward.

**Comment by suryag10** [comment]
Thx Kevin.

**Comment by kevin-bates** [comment]
Since this is being addressed in #1000, I'm going to close this issue (see also #957).
