### ISSUE TITLE
Ability to run nbclient with enterprise-gateway

### ISSUE THREAD

**Issue by achandak123** [jupyter/enterprise_gateway#972]
## Description
We use Enterprise-gateway (EG) with kubernetes, wherein each kernel is launched in a separate pod (in a different namespace). Jupyterlab with EG works fine for us.
However, we want to be able to run .ipynb programmatically, without going to jupyter lab UI. So, more like using nbclient. I looked at the documentation [here](https://github.com/jupyter/enterprise_gateway/blob/6c227e67265744398c4625dc64e2c65bb92045d2/docs/source/kernel-library.md), however i am not clear how to use. When we launch jupter server, we specify the gateway url via ```--gateway-url```. How do we tell nbclient to use the EG in a similar fashion?

## Screenshots / Logs
If applicable, add screenshots and/or logs to help explain your problem.
To generate better logs, please run the gateway with `--debug` command line parameter.

## Environment

- Enterprise Gateway Version [e.g. 1.x, 2.x, ...]
elyra/enterprise-gateway:2.5.0

- Platform: [e.g. YARN, Kubernetes ...]
Kubernetes

- Others [e.g. Jupyter Server 5.7, JupyterHub 1.0, etc]
```
(base) jovyan@jupyterlab-85c749c644-jcczh:~$ jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.2.0
qtconsole        : not installed
ipython          : 7.21.0
ipykernel        : 5.5.0
jupyter client   : 6.1.12
/opt/conda/lib/python3.8/site-packages/jupyter_server/transutils.py:13: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  warnings.warn(warn_msg, FutureWarning)
jupyter lab      : 3.0.12
nbconvert        : 5.6.1
ipywidgets       : not installed
nbformat         : 5.1.2
traitlets        : 5.0.5
```

**Comment by kevin-bates** [comment]
Using `RemoteKernelManager` directly allows applications to launch remote kernels _from_ that application, not redirect to an EG server (as is the case with `--gateway-url`).   For Kubernetes, this would require that nbclient (or whatever application is using nbclient) to also be running in Kuberenetes, which you may not want.

If instead, you wanted behavior similar to `--gateway-url`, where the client application is outside Kubernetes, but is targeting an EG server hosted within Kubernetes, then you'd probably want to take a look at [`GatewayKernelManager`](https://github.com/jupyter-server/jupyter_server/blob/3343101cd97b587c580adc75ec27c6047ab86f30/jupyter_server/gateway/managers.py#L301) that was recently moved from Elyra to Jupyter Server.  Elyra uses this via Papermill (which uses nbclient) to launch EG-hosted kernels. However, Elyra _is_ a Jupyter Server extension.  That said, `GatewayKernelManager` (and `GatewayKernelClient`) are intended to be run directly - although I haven't attempted that (until just now)...

```python
import nbformat
from nbclient import NotebookClient
from jupyter_server.gateway.managers import GatewayKernelManager

with open("my_notebook.ipynb") as fp:
    test_notebook = nbformat.read(fp, as_version=4)

client = NotebookClient(nb=test_notebook, kernel_manager_class=GatewayKernelManager)
client.execute()
```
I also set env `JUPYTER_GATEWAY_URL` to what I'd normally use for `--gateway-url`.  I'm not sure how the various [`GatewayClient` config options](https://github.com/jupyter-server/jupyter_server/blob/master/jupyter_server/gateway/gateway_client.py) can be set via configuration files, but all are also exposed via envs (all using `JUPYTER_GATEWAY_` as their prefix), so that might be your best option for now.

Also keep in mind that `GatewayKernelManager` and `GatewayKernelClient` are probably limited on their ability to truly emulate KernelManager and KernelClient instances, but if you constrain that domain to what nbclient uses, you're probably okay.

Please let me know how this goes for you.   We can keep this issue open until we've finished the conversation here.

**Comment by achandak123** [comment]
Thanks @kevin-bates for your prompt response. I just tried it
```
(base) jovyan@jupyterlab-85c749c644-jcczh:~$ cat test.py
import nbformat
from nbclient import NotebookClient
from jupyter_server.gateway.managers import GatewayKernelManager

with open("/home/jovyan/workflow.ipynb") as fp:
    test_notebook = nbformat.read(fp, as_version=4)

client = NotebookClient(nb=test_notebook, kernel_manager_class=GatewayKernelManager)
client.execute()

(base) jovyan@jupyterlab-85c749c644-jcczh:~$ python test.py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    client.execute()
  File "/opt/conda/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/conda/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/conda/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.8/site-packages/nbclient/client.py", line 537, in async_execute
    async with self.async_setup_kernel(**kwargs):
  File "/opt/conda/lib/python3.8/site-packages/async_generator/_util.py", line 34, in __aenter__
    return await self._agen.asend(None)
  File "/opt/conda/lib/python3.8/site-packages/nbclient/client.py", line 475, in async_setup_kernel
    self.km = self.create_kernel_manager()
  File "/opt/conda/lib/python3.8/site-packages/nbclient/client.py", line 358, in create_kernel_manager
    if self.km.client_class == 'jupyter_client.client.KernelClient':
AttributeError: 'GatewayKernelManager' object has no attribute 'client_class'
```

I am looking into error as well, just posting it here, if you have a quick fix for this.

**Comment by kevin-bates** [comment]
This implies you're not using at least Jupyter Server 1.7.0 (the latest is 1.8.0).  Please upgrade `jupyter_server` and you should get further along.  When I moved the class from Elyra, the only "multi" KernelManager was named `GatewayKernelManager`.  It is now named `GatewayMappingKernelManager` and the moved class is `GatewayKernelManager` - which specifies the `client_class` attribute.

**Comment by achandak123** [comment]
Thanks a lot @kevin-bates , that was the issue.
```
(base) Amits-MacBook-Pro:~ amit$ jupyter-server --version
1.7.0
```
Once i  upgraded and I just set the ```JUPYTER_GATEWAY_URL```, it worked

```
(base) MacBook-Pro:~ amit$ cat test.py
import nbformat
from nbclient import NotebookClient
from jupyter_server.gateway.managers import GatewayKernelManager

with open("/Users/amit/Downloads/workflow.ipynb") as fp:
    test_notebook = nbformat.read(fp, as_version=4)

client = NotebookClient(nb=test_notebook, kernel_manager_class=GatewayKernelManager)
resp = client.execute()
print(resp)
(base) MacBook-Pro:~ amit$ python test.py
{'metadata': {'language_info': {'name': 'python', 'version': '3.7.6', 'mimetype': 'text/x-python', 'codemirror_mode': {'name': 'ipython', 'version': 3}, 'pygments_lexer': 'ipython3', 'nbconvert_exporter': 'python', 'file_extension': '.py'}, 'kernelspec': {'name': 'python_kubernetes', 'display_name': 'Python on Kubernetes', 'language': 'python'}, 'toc-autonumbering': False}, 'nbformat_minor': 5, 'nbformat': 4, 'cells': [{'cell_type': 'code', 'source': 'print("hello print")', 'metadata': {'execution': {'iopub.status.busy': '2021-05-24T21:00:05.991955Z', 'iopub.execute_input': '2021-05-24T21:00:05.997793Z', 'iopub.status.idle': '2021-05-24T21:00:06.001943Z', 'shell.execute_reply': '2021-05-24T21:00:06.002002Z'}}, 'execution_count': 1, 'outputs': [{'output_type': 'stream', 'name': 'stdout', 'text': 'hello print\n'}], 'id': '41f225f6'}]}
```

I will look into the URL can be passed as an argument, rather than using environment variable.
I will close this issue.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/run-ipynb-programmatically/9270/5

**Comment by kevin-bates** [comment]
This is pure speculation, but I _think_ if you were to contain your nbclient call in a class that derives from traitlets' [`Application` class](https://github.com/ipython/traitlets/blob/191ff75e93d56446b2c051f4dbb33e2f0e7be71d/traitlets/config/application.py#L119) and [added `GatewayClient` to a `classes[]` attribute](https://github.com/jupyter-server/jupyter_server/blob/3343101cd97b587c580adc75ec27c6047ab86f30/jupyter_server/serverapp.py#L592-L596), then configurable traits on `GatewayClient` could be available on the command line via `--GatewayClient.url=http://foo.com:8947`.

For example, here's partial output from `jupyter-server --help-all`...
```
--GatewayClient.request_timeout=<Float>
    The time allowed for HTTP request completion.
    (JUPYTER_GATEWAY_REQUEST_TIMEOUT env var)
    Default: 40.0
--GatewayClient.url=<Unicode>
    The url of the Kernel or Enterprise Gateway server where kernel
    specifications are defined and kernel management takes place. If defined,
    this Notebook server acts as a proxy for all kernel management and kernel
    specification retrieval.  (JUPYTER_GATEWAY_URL env var)
    Default: None
--GatewayClient.validate_cert=<Bool>
    For HTTPS requests, determines if server's certificate should be validated
    or not. (JUPYTER_GATEWAY_VALIDATE_CERT env var)
    Default: True
--GatewayClient.ws_url=<Unicode>
    The websocket url of the Kernel or Enterprise Gateway server.  If not
    provided, this value will correspond to the value of the Gateway url with
    'ws' in place of 'http'.  (JUPYTER_GATEWAY_WS_URL env var)
    Default: None
```
It's my understanding that the application gets its set of CLI-configurable classes from the `classes` attribute.
