### ISSUE TITLE
Enterprise gateway is not able to launch the kernel

### ISSUE THREAD

**Issue by achandak123** [jupyter/enterprise_gateway#975]
## Description
I am running the enterprise gateway inside k8, using the helm chart [here](https://github.com/jupyter/enterprise_gateway/tree/master/etc/kubernetes/helm/enterprise-gateway). 
On my jupyter notebook, i am able to get the list of kernels suppported, as thats just a REST call to EG, i guess. However, when i have selected a kernel, it doesnt come up, as EG is not able to communicate with k8 master looks like.

The EG is launched with a service account, which gives it access to all the required apis, so not sure, what wrong in here?

## Screenshots / Logs
[D 2021-06-21 18:55:17.978 EnterpriseGatewayApp] Launching kernel: 'Python on Kubernetes' with command: ['/opt/conda/bin/python3.7', '/usr/local/share/jupyter/kernels/python_kubernetes/scripts/launch_kubernetes.py', '--RemoteProcessProxy.kernel-id', '2d18cc6d-fbcd-48b3-ba97-efe97c3058ba', '--RemoteProcessProxy.port-range', '0..0', '--RemoteProcessProxy.response-address', '10.1.156.69:37587']
[W 210621 18:57:29 connectionpool:750] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd567f0fc10>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/v1/namespaces
[W 210621 18:59:40 connectionpool:750] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd567f183d0>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/v1/namespaces
[W 210621 19:01:51 connectionpool:750] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd567f18590>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/v1/namespaces
[D 2021-06-21 19:04:02.360 EnterpriseGatewayApp] response socket still open, close it
[E 2021-06-21 19:04:02.361 EnterpriseGatewayApp] Error occurred creating namespace 'jovyan-2d18cc6d-fbcd-48b3-ba97-efe97c3058ba': HTTPSConnectionPool(host='10.152.183.1', port=443): Max retries exceeded with url: /api/v1/namespaces (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd567f18750>: Failed to establish a new connection: [Errno 110] Connection timed out'))
[I 210621 19:04:02 web:2250] 200 GET /api/kernels (10.62.1.191) 4.99ms

## Environment

- Enterprise Gateway Version 
elyra/enterprise-gateway:2.5.0

- Platform: 
Kubernetes

- Others
Jupyterlab - 3.0.12

- Kubernetes version
`ubuntu@ip-10-68-1-92:~/jeg$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-13T02:40:46Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-34+984a1cd176537e", GitCommit:"984a1cd176537e2d36d7db36e49e787e1c42a0aa", GitTreeState:"clean", BuildDate:"2021-06-11T05:08:05Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
ubuntu@ip-10-68-1-92:~/jeg$`

**Comment by kevin-bates** [comment]
Hi @achandak123.  It looks like there's an issue with the namespace API and EG is unable to (by default) create the namespace for the kernel.  There are a couple of things you can do to try to "get things minimally working" that will by-pass the EG code that creates a namespace.  This way, you might determine if your issue is specific to namespace creation or something more general.

1. You can set `EG_SHARED_NAMESPACE` to True.  When true, EG will use its namespace ('enterprise-gateway' by default) as the kernel's namespace.  Of course, this means that all kernels will reside in a single namespace.  Some deployments want this, others don't.
2. You can set `KERNEL_NAMESPACE` on your client-side environment to the name of the desired namespace.  This value will automatically propagate from the client - down into the kernel launch logic of EG.  If using this approach, EG assumes that the named namespace already exists and does nothing to validate or modify it.  Although similar to using a shared namespace, this approach gives you a bit more flexibility and allows admins to apply resource limits, etc. to that specific namespace.

If you find that the kernel pod can be created with either of these approaches, then we might need to take a closer look at what might be happening.  Frankly, I'm surprised there isn't more noise in the logs since you have DEBUG enabled.

**Comment by achandak123** [comment]
> Hi @achandak123. It looks like there's an issue with the namespace API and EG is unable to (by default) create the namespace for the kernel. There are a couple of things you can do to try to "get things minimally working" that will by-pass the EG code that creates a namespace. This way, you might determine if your issue is specific to namespace creation or something more general.
> 
> 1. You can set `EG_SHARED_NAMESPACE` to True.  When true, EG will use its namespace ('enterprise-gateway' by default) as the kernel's namespace.  Of course, this means that all kernels will reside in a single namespace.  Some deployments want this, others don't.
> 2. You can set `KERNEL_NAMESPACE` on your client-side environment to the name of the desired namespace.  This value will automatically propagate from the client - down into the kernel launch logic of EG.  If using this approach, EG assumes that the named namespace already exists and does nothing to validate or modify it.  Although similar to using a shared namespace, this approach gives you a bit more flexibility and allows admins to apply resource limits, etc. to that specific namespace.
> 
> If you find that the kernel pod can be created with either of these approaches, then we might need to take a closer look at what might be happening. Frankly, I'm surprised there isn't more noise in the logs since you have DEBUG enabled.

Thanks @kevin-bates for the prompt response. Yes, i can try those options you mentioned, however my concern is this issue is more about not able to communicate with k8 apis? Not very specific to namespace creation only. So, i checked the rolebinding in the helm and it does have the required roles. 
I wil try and get back to you. Thanks

**Comment by achandak123** [comment]
Hi @kevin-bates , as suspected, that config didnt help
```
[D 2021-06-26 00:38:10.988 EnterpriseGatewayApp] RemoteMappingKernelManager.start_kernel: python_kubernetes, kernel_username: jovyan
[D 2021-06-26 00:38:11.041 EnterpriseGatewayApp] Instantiating kernel 'Python on Kubernetes' with process proxy: enterprise_gateway.services.processproxies.k8s.KubernetesProcessProxy
[D 2021-06-26 00:38:11.334 EnterpriseGatewayApp] Response socket launched on '10.1.168.133:49171' using 5.0s timeout
[D 2021-06-26 00:38:11.335 EnterpriseGatewayApp] Starting kernel (async): ['/opt/conda/bin/python3.7', '/usr/local/share/jupyter/kernels/python_kubernetes/scripts/launch_kubernetes.py', '--RemoteProcessProxy.kernel-id', 'eed45303-bda6-4b1b-8cfa-8dc756404f8c', '--RemoteProcessProxy.port-range', '0..0', '--RemoteProcessProxy.response-address', '10.1.168.133:49171']
[D 2021-06-26 00:38:11.335 EnterpriseGatewayApp] Launching kernel: 'Python on Kubernetes' with command: ['/opt/conda/bin/python3.7', '/usr/local/share/jupyter/kernels/python_kubernetes/scripts/launch_kubernetes.py', '--RemoteProcessProxy.kernel-id', 'eed45303-bda6-4b1b-8cfa-8dc756404f8c', '--RemoteProcessProxy.port-range', '0..0', '--RemoteProcessProxy.response-address', '10.1.168.133:49171']
[W 2021-06-26 00:38:11.335 EnterpriseGatewayApp] Shared namespace has been configured.  All kernels will reside in EG namespace: eg
[D 2021-06-26 00:38:11.335 EnterpriseGatewayApp] BaseProcessProxy.launch_process() env: {'SHELL': '/bin/bash', 'KUBERNETES_SERVICE_PORT_HTTPS': '443', 'EG_MIRROR_WORKING_DIRS': 'False', 'KUBERNETES_SERVICE_PORT': '443', 'ENTERPRISE_GATEWAY_PORT_8877_TCP': 'tcp://10.152.183.232:8877', 'EG_NAMESPACE': 'eg', 'ENTERPRISE_GATEWAY_SERVICE_PORT_HTTP': '8888', 'HOSTNAME': 'enterprise-gateway-74cbdf5df7-gqnn9', 'LANGUAGE': 'en_US.UTF-8', 'EG_SHARED_NAMESPACE': 'True', 'EG_PORT': '8888', 'EG_LOG_LEVEL': 'DEBUG', 'JAVA_HOME': '/usr/lib/jvm/java-8-openjdk-amd64', 'ENTERPRISE_GATEWAY_SERVICE_PORT_RESPONSE': '8877', 'EG_KERNEL_WHITELIST': '"r_kubernetes","python_kubernetes","python_tf_kubernetes","python_tf_gpu_kubernetes","scala_kubernetes","spark_r_kubernetes","spark_python_kubernetes","spark_scala_kubernetes"', 'NB_UID': '1000', 'ENTERPRISE_GATEWAY_SERVICE_HOST': '10.152.183.232', 'PWD': '/usr/local/bin', 'ENTERPRISE_GATEWAY_PORT_8877_TCP_PROTO': 'tcp', 'EG_CULL_IDLE_TIMEOUT': '3600', 'EG_DEFAULT_KERNEL_NAME': 'python_kubernetes', 'ENTERPRISE_GATEWAY_PORT_8888_TCP_PORT': '8888', 'MINICONDA_MD5': '87e77f097f6ebb5127c77662dfc3165e', 'EG_ENABLE_TUNNELING': 'False', 'ENTERPRISE_GATEWAY_PORT_8888_TCP_ADDR': '10.152.183.232', 'EG_KERNEL_LAUNCH_TIMEOUT': '60', 'HOME': '/home/jovyan', 'LANG': 'en_US.UTF-8', 'KUBERNETES_PORT_443_TCP': 'tcp://10.152.183.1:443', 'ENTERPRISE_GATEWAY_PORT_8877_TCP_PORT': '8877', 'EG_LIST_KERNELS': 'True', 'EG_SSH_PORT': '2122', 'NB_GID': '100', 'EG_RESPONSE_PORT': '8877', 'ENTERPRISE_GATEWAY_PORT_8888_TCP': 'tcp://10.152.183.232:8888', 'KG_PORT': '8888', 'EG_CULL_CONNECTED': 'False', 'EG_PORT_RETRIES': '0', 'KG_IP': '0.0.0.0', 'ENTERPRISE_GATEWAY_PORT_8877_TCP_ADDR': '10.152.183.232', 'EG_CULL_INTERVAL': '60', 'EG_IP': '0.0.0.0', 'SHLVL': '0', 'CONDA_DIR': '/opt/conda', 'MINICONDA_VERSION': '4.8.2', 'ENTERPRISE_GATEWAY_SERVICE_PORT': '8888', 'SPARK_HOME': '/opt/spark', 'KUBERNETES_PORT_443_TCP_PROTO': 'tcp', 'KG_PORT_RETRIES': '0', 'KUBERNETES_PORT_443_TCP_ADDR': '10.152.183.1', 'SPARK_VER': '2.4.6', 'ENTERPRISE_GATEWAY_PORT': 'tcp://10.152.183.232:8888', 'CONDA_VERSION': '4.8.2', 'NB_USER': 'jovyan', 'KUBERNETES_SERVICE_HOST': '10.152.183.1', 'ENTERPRISE_GATEWAY_PORT_8888_TCP_PROTO': 'tcp', 'LC_ALL': 'en_US.UTF-8', 'KUBERNETES_PORT': 'tcp://10.152.183.1:443', 'KUBERNETES_PORT_443_TCP_PORT': '443', 'PATH': '/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'EG_KERNEL_CLUSTER_ROLE': 'kernel-controller', 'DEBIAN_FRONTEND': 'noninteractive', 'KERNEL_LAUNCH_TIMEOUT': '40', 'KERNEL_USERNAME': 'jovyan', 'KERNEL_GATEWAY': '1', 'KERNEL_POD_NAME': 'jovyan-eed45303-bda6-4b1b-8cfa-8dc756404f8c', 'KERNEL_SERVICE_ACCOUNT_NAME': 'default', 'KERNEL_NAMESPACE': 'eg', 'KERNEL_IMAGE': 'elyra/kernel-py:2.5.0', 'KERNEL_EXECUTOR_IMAGE': 'elyra/kernel-py:2.5.0', 'KERNEL_UID': '1000', 'KERNEL_GID': '100', 'EG_MIN_PORT_RANGE_SIZE': '1000', 'EG_MAX_PORT_RANGE_RETRIES': '5', 'KERNEL_ID': 'eed45303-bda6-4b1b-8cfa-8dc756404f8c', 'KERNEL_LANGUAGE': 'python', 'EG_IMPERSONATION_ENABLED': 'False'}
[I 2021-06-26 00:38:11.339 EnterpriseGatewayApp] KubernetesProcessProxy: kernel launched. Kernel image: elyra/kernel-py:2.5.0, KernelID: eed45303-bda6-4b1b-8cfa-8dc756404f8c, cmd: '['/opt/conda/bin/python3.7', '/usr/local/share/jupyter/kernels/python_kubernetes/scripts/launch_kubernetes.py', '--RemoteProcessProxy.kernel-id', 'eed45303-bda6-4b1b-8cfa-8dc756404f8c', '--RemoteProcessProxy.port-range', '0..0', '--RemoteProcessProxy.response-address', '10.1.168.133:49171']'
[W 210626 00:40:21 connectionpool:750] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f46560b3b10>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/v1/namespaces/eg/pods?labelSelector=kernel_id%3Deed45303-bda6-4b1b-8cfa-8dc756404f8c
```
The issue is EG is not able to talk to the k8 apis.

**Comment by kevin-bates** [comment]
I agree with the premise of your assessment.  Do you see the kernel pod at all?  The pod gets created via the `launch_kubernetes.py` script located in the kernelspec's `scripts` directory.  Although it too uses the k8s client API, this might provide another datapoint since that script is invoked from a subprocess.  All that EG is trying to do following the kernel's launch is locate the kernel pod using its labels, one of which specifies the kernel's id (that EG knows about).

Also, I notice your EG namespace is 'eg'.  In case there's some hard coding of the default namespace somewhere, it might be helpful to create a namespace of 'enterprise-gateway' - just to help eliminate that possibility.  (I doubt that will help.)

Since I'm not in a position to try this, nor have heard of this happening, I can only help figure out ways to troubleshoot.

**Comment by achandak123** [comment]
Thanks @kevin-bates. The issue came out to be a default route issue, we were running vpn client along with EG and the default route point to the tunnel, so EG couldnt talk to k8, sorry for the trouble.

**Comment by kevin-bates** [comment]
No worries. I'm glad you're moving forward and really appreciate the follow up.
