### ISSUE TITLE
Running notebook programmatically, nbclient doesnt use the kernel from the kernelspec

### ISSUE THREAD

**Issue by achandak123** [jupyter/enterprise_gateway#978]
## Description
As a followup of [this](https://github.com/jupyter/enterprise_gateway/issues/972) issue, i created a custom python kubernetes based kernel with boto3 package installed in it. When i run the jupyterlab server against this Enterprise gateway (EG) and chose the custom kernel,  i am able to use boto3.

However, when i try running nbClient like this
```
client = NotebookClient(nb=newNb, kernel_manager_class=GatewayKernelManager)
```
I see that EG is launching Python3 kernel, instead of my custom kernel.

This is because of the [this](https://github.com/jupyter-server/jupyter_server/blob/e3b2dada0ae305d4512476ff664b612a87c5bc50/jupyter_server/gateway/managers.py#L398) code, i think.

Was wondering how can i override it to use the custom Kernel, when i call it from nbClient itself?

## Screenshots / Logs
When kernel is launched using the jupyterlab server, it picks up the custom kernel
```
[D 2021-07-08 23:21:04.120 EnterpriseGatewayApp] Launching kernel: 'custom Kernel' with command: ['/opt/conda/bin/python3.7', '/usr/local/share/jupyter/kernels/python_kubernetes/scripts/launch_kubernetes.py', '--RemoteProcessProxy.kernel-id', '1635c0a0-5b8a-4f58-b204-c1b5cab0d8d0', '--RemoteProcessProxy.port-range', '0..0', '--RemoteProcessProxy.response-address', '10.1.61.18:37037']
```

However, when i am running using nbClient, although the **kernelspec** in the ipynb file says "custom Kernel", it picks Python 3 as the kernel.

```
[D 2021-07-09 01:11:32.445 EnterpriseGatewayApp] Launching kernel: 'Python 3' with command: ['/opt/conda/bin/python', '-m', 'ipykernel_launcher', '-f', '/home/jovyan/.local/share/jupyter/runtime/kernel-cacd2a85-d5a9-418f-86db-cede2b136617.json']
[D 2021-07-09 01:18:46.316 EnterpriseGatewayApp] Launching kernel: 'Python 3' with command: ['/opt/conda/bin/python', '-m', 'ipykernel_launcher', '-f', '/home/jovyan/.local/share/jupyter/runtime/kernel-f1bb0ba9-9957-4d54-b213-d2987cbe6ee5.json']
[D 2021-07-09 01:27:59.464 EnterpriseGatewayApp] Launching kernel: 'Python 3' with command: ['/opt/conda/bin/python', '-m', 'ipykernel_launcher', '-f', '/home/jovyan/.local/share/jupyter/runtime/kernel-7b822ef6-1230-4691-869d-47415587e432.json']
```

## Environment

- Enterprise Gateway Version 
   elyra/enterprise-gateway:2.5.0

- Platform: Kubernetes

- Others [e.g. Jupyter Server 5.7, Jup

```
(base) jovyan@jupyterlab-85c749c644-jcczh:~$ jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.2.0
qtconsole        : not installed
ipython          : 7.21.0
ipykernel        : 5.5.0
jupyter client   : 6.1.12
/opt/conda/lib/python3.8/site-packages/jupyter_server/transutils.py:13: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  warnings.warn(warn_msg, FutureWarning)
jupyter lab      : 3.0.12
nbconvert        : 5.6.1
ipywidgets       : not installed
nbformat         : 5.1.2
traitlets        : 5.0.5
```

**Comment by achandak123** [comment]
I tried passing kernel_name to nbclient like this 
```
client = NotebookClient(nb=test_notebook, kernel_name="python_kubernetes", kernel_manager_class=GatewayKernelManager)
```

still didnt help.

**Comment by achandak123** [comment]
Figured out the issue 
```
resp = client.execute(kernel_name="python_kubernetes")
```

seems to do the trick.
Let me know if there is a better way.

**Comment by kevin-bates** [comment]
Hmm.  Looking into the `nbclient` code, setting the kernel_name at the point of `client.execute()` should really be no different than setting it during construction.

The code you reference merely uses the "python3" kernel as a default when it doesn't find a value for `kernel_name` - so it seems like the focus should be on _how is the `kernel_name` parameter used/stored during `NotebookClient` construction?_

Have you tried stepping through nbclient construction and `execute()` in a debugger?  It's like the construction is not recognizing `kernel_name` (obviously).

I see that nbclient exposes an `execute()` method that merely constructs an instance and calls _its_ `execute()` method.  It would be interesting to know if using `NotebookClient.execute()` would behave any differently.

**Comment by chiawchen** [comment]
I recently have a need to run notebook with a remote kernel hosted by JEG and have the same issue as @achandak123 mentioned in the thread. After digging into how `nbclient` works, I found that `NotebookClient().execute` is actually just a wrapper to run the `run_sync` as [here](https://github.com/jupyter/nbclient/blob/fa3ca3760bebd416efaf44b06d2a1f9c6038c8e8/nbclient/client.py#L714) 

```
In [1]: from nbclient import NotebookClient

In [2]: client = NotebookClient(nb=None)

In [3]: client.execute
Out[3]: <bound method run_sync.<locals>.wrapped of <nbclient.client.NotebookClient object at 0x7f54a3ed6d50>>
```

so I turn to check how `run_sync` is working, and interestingly it seems like any extra argument that been passed into this function (`**kwargs`) will be directly passed to `self.kernel_manager_class.start_kernel()` as it mentioned [here](https://github.com/jupyter/nbclient/blob/fa3ca3760bebd416efaf44b06d2a1f9c6038c8e8/nbclient/client.py#L674) 
```
        async with self.async_setup_kernel(**kwargs):
            assert self.kc is not None
            self.log.info("Executing notebook with kernel: %s" % self.kernel_name)
```
and going forward to the [place](https://github.com/jupyter-server/jupyter_server/blob/32e0919270dd2128708cbb2ebf837324e84ecb47/jupyter_server/gateway/managers.py#L417) where `start_kernel` actually been run in `GatewayKernelManager`, we can see it's extracting out kernel_name based on `**kwargs` purely, 
```
    async def start_kernel(self, **kwargs):
        """Starts a kernel via HTTP in an asynchronous manner.
        Parameters
        ----------
        `**kwargs` : optional
             keyword arguments that are passed down to build the kernel_cmd
             and launching the kernel (e.g. Popen kwargs).
        """
        kernel_id = kwargs.get("kernel_id")

        if kernel_id is None:
            kernel_name = kwargs.get("kernel_name", "python3")
```
and because in `nbclient` we didn't pass `self.kernel_name` as an argument to `self.async_setup_kernel(**kwargs)` so it's causing GatewayKernelManager side failed to use the `kernel_name` been initialized in construction time

A quick fix may be just modified this [line] (https://github.com/jupyter/nbclient/blob/fa3ca3760bebd416efaf44b06d2a1f9c6038c8e8/nbclient/client.py#L691) in nbclient's `async_execute` method
```
    async with self.async_setup_kernel(kernel_name=self.kernel_name, **kwargs):
```

**Comment by kevin-bates** [comment]
Thanks @chiawchen - just so I'm clear, are you suggesting that what we document [here](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/developers/kernel-manager.html) in our _Developer's Guide_ doesn't work?

Unless something recently changed in `nbclient` this approach has been working for some time now.

**Comment by chiawchen** [comment]
To run it correctly on my end, I need to do the `client.execute(kernel_name=...)` manually, setting it in the `NotebookClient` constructor time doesn't propagate down to `GatewayKernelManager`
Below are my client side related library version
```
$ jupyter --version
Selected Jupyter core packages...
IPython          : 7.34.0
ipykernel        : not installed
ipywidgets       : not installed
jupyter_client   : 7.3.5
jupyter_core     : 4.11.1
jupyter_server   : 1.18.1
jupyterlab       : not installed
nbclient         : 0.6.8
nbconvert        : 7.0.0
nbformat         : 5.5.0
notebook         : not installed
qtconsole        : not installed
traitlets        : 5.4.0
```
server side using JEG 3.0.0dev

**Comment by kevin-bates** [comment]
Ah - yes, I agree.  I suspect when I ran those examples, I had probably set the kernel to `python` or `python3` - which also happens to be the default kernel, so the code worked. 

Would you like to update the docs?  I believe that both [_Standalone Remote Kernel Execution_](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/developers/kernel-library.html#standalone-remote-kernel-execution) and [_Using Jupyter Server’s GatewayKernelManager_](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/developers/kernel-manager.html) require updates that _move_ `kernel_name` from the constructor to the `execute()` method.

**Comment by chiawchen** [comment]
SG, let me update the docs accordingly!
