### ISSUE TITLE
yarn_api_client error occurs when anonymous and kerberos are both disabled

### ISSUE THREAD

**Issue by abzymeinsjtu** [jupyter/enterprise_gateway#979]
## Description

I'm now testing enterprise gateway with spark_python_cluster_kernel at aliyun EMR Cluster and a yarn_api_client error occurs when the kernel is starting,  because my hadoop configuration `hadoop.http.authentication.simple.anonymous.allowed` is false while kerberos is not enabled.

I check configuration doc and find nothing about the way to set a username in api（simply add a user.name param of endpoint just work when anonymous and kerberos are both disabled, such as http://{rm_endpoint}/ws/v1/cluster?user.name=hadoop）.

Maybe it's nice to have the case supported when such configuration comes.

## Screenshots / Logs

![截屏2021-07-14 下午9 39 00](https://user-images.githubusercontent.com/4393648/125631809-f590352a-bd6a-4cbd-8c28-b3293b0540b7.png)

## Environment

- Enterprise Gateway Version [2.5]
- Platform: [YARN 3.1.2]

**Comment by kevin-bates** [comment]
Hi @abzymeinsjtu - your request makes sense but I think there may be changes required both in EG and in [`yarn_api_client`](https://github.com/CODAIT/hadoop-yarn-api-python-client).  I recommend opening an issue/question in the yarn-api-client repo to determine how to address the issue, then we can look into the kinds of changes necessary in EG.  We might even find that there's already a way to address this and only EG requires changes.

I'm copying @dimon222, who is quite knowledgeable about the Hadoop YARN REST API and yarn-api-client.

**Comment by kevin-bates** [comment]
Hi @abzymeinsjtu - @dimon222 has provided a possible solution in his PR.  Are you able to take his branch and try things out?

I'm not exactly sure how we would surface this in EG.  My initial thought, if it works, would be to make this the default case.  So this code in `yarn.py` would look as follows...

https://github.com/jupyter/enterprise_gateway/blob/d30cf13fc4521b7ff0b594b93a43c70d9c50f334/enterprise_gateway/services/processproxies/yarn.py#L68-L71

```python
        if self.yarn_endpoint_security_enabled:
            from requests_kerberos import HTTPKerberosAuth
            auth = HTTPKerberosAuth()
        else:
            auth = SimpleAuth()
```
with the additional import at top of file of: `from yarn_api_client.auth import SimpleAuth`.

If this can't be done as the default case, then we'd need an additional configuration option or change `yarn_endpoint_scurity_enabled` to a non-boolean that specifies 'Kerberos', 'Simple' or `None` - or something like that.  This option, of course, would cause issues with existing installations, so we'd likely need to introduce a separate (but similar) config option such that `yarn_endpoint_security_enabled` implies `Kerberos`.

My Hadoop cluster was previously unavailable, but I'm hoping I can play with this as well.

**Comment by dimon222** [comment]
@kevin-bates One more extra thing is SimpelAuth now needs to accept the name of user account that it will try to impersonate during simple auth. I'm not 100% sure about if EG is offering the facility to do so, but I could guess for now it can be hardcoded to something like "hadoop" for testing reasons.

**Comment by abzymeinsjtu** [comment]
> things

yup, this seems to be compatible event with anonymous enabled.

i will try it out using Aliyun EMR cluster

**Comment by abzymeinsjtu** [comment]
> > things
> 
> yup, this seems to be compatible event with anonymous enabled.
> 
> i will try it out using Aliyun EMR cluster

**Comment by abzymeinsjtu** [comment]
> Hi @abzymeinsjtu - @dimon222 has provided a possible solution in his PR. Are you able to take his branch and try things out?
> 
> I'm not exactly sure how we would surface this in EG. My initial thought, if it works, would be to make this the default case. So this code in `yarn.py` would look as follows...
> 
> https://github.com/jupyter/enterprise_gateway/blob/d30cf13fc4521b7ff0b594b93a43c70d9c50f334/enterprise_gateway/services/processproxies/yarn.py#L68-L71
> 
> ```python
>         if self.yarn_endpoint_security_enabled:
>             from requests_kerberos import HTTPKerberosAuth
>             auth = HTTPKerberosAuth()
>         else:
>             auth = SimpleAuth()
> ```
> 
> with the additional import at top of file of: `from yarn_api_client.auth import SimpleAuth`.
> 
> If this can't be done as the default case, then we'd need an additional configuration option or change `yarn_endpoint_scurity_enabled` to a non-boolean that specifies 'Kerberos', 'Simple' or `None` - or something like that. This option, of course, would cause issues with existing installations, so we'd likely need to introduce a separate (but similar) config option such that `yarn_endpoint_security_enabled` implies `Kerberos`.
> 
> My Hadoop cluster was previously unavailable, but I'm hoping I can play with this as well.

yup, this seems to be compatible event with anonymous enabled.

and as Dmitry @dimon222 mentioned that a user name should be configured in EG to impersionate, and in Aliyun EMR Cluster i'll use `hadoop` as default to try out
