### ISSUE TITLE
Configuration option to restrict requests to origin

### ISSUE THREAD

**Issue by bgerrity** [jupyter/enterprise_gateway#989]
## Problem

Jupyter Enterprise Gateway [assumes](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/getting-started-security.html#security-features) that all users issuing requests are authenticated. 

For my purposes, a reverse proxy is responsible for that user authentication. I'd like to be able to configure the gateway to reject any requests that don't originate from that origin.

## Proposition

I was wondering if there was any interest in adding this as a configuration option? Or perhaps there's already a (better) way to achieve the same effect? I was planning on monkey patching tornado for my specific use case but I wanted to ask if there were a shared interest, in which case, it'd be easiest to cut a PR.

**Comment by kevin-bates** [comment]
Hi @bgerrity - I think this is a great idea and, since many of the maintainers are not experts in this area, would greatly appreciate your help (and contribution).  Thank you.

I'd like to cut a 2.6 release sometime this week or next, so it would be fantastic if this can make it in.

**Comment by bgerrity** [comment]
Sorry about the hold up in getting the changes published: I've opened a PR #997.

**Comment by kevin-bates** [comment]
Addressed in #997
