### ISSUE TITLE
spark python on YARN cluster kernel fail to complete object function

### ISSUE THREAD

**Issue by abzymeinsjtu** [jupyter/enterprise_gateway#996]
## Description

i'm trying to run a spark python kernel on YARN with EG, both of client and cluster mode.
Then i have a problem about code completion under cluster mode while client mode is ok, that i can not complete any function of an object.

## Screenshots / Logs

my yarn cluster kernel config is 

```
{
  "language": "python",
  "display_name": "Spark - Python (YARN Cluster Mode)",
  "metadata": {
    "process_proxy": {
      "class_name": "enterprise_gateway.services.processproxies.yarn.YarnClusterProcessProxy"
    }
  },
  "env": {
    "HADOOP_CONF_DIR": "/etc/ecm/hadoop-conf",
    "SPARK_HOME": "/usr/lib/spark-current",
    "PYSPARK_PYTHON": "/usr/lib/miniconda3/bin/python",
    "PYTHONPATH": "/usr/lib/miniconda3/lib/python3.7/site-packages:/usr/lib/spark-current/python:/usr/lib/spark-current/python/lib/py4j-0.10.7-src.zip",
    "SPARK_OPTS": "--master yarn --deploy-mode cluster --name ${KERNEL_ID:-ERROR__NO__KERNEL_ID} --conf spark.yarn.submit.waitAppCompletion=false --conf spark.yarn.appMasterEnv.PYTHONUSERBASE=/usr/lib/miniconda3 --conf spark.yarn.appMasterEnv.PYTHONPATH=/usr/lib/miniconda3/lib/python3.7/site-packages:/usr/lib/spark-current/python:/usr/lib/spark-current/python/lib/py4j-0.10.6-src.zip --conf spark.yarn.appMasterEnv.PATH=/usr/lib/miniconda3/bin:$PATH ${KERNEL_EXTRA_SPARK_OPTS}",
    "LAUNCH_OPTS": ""
  },
  "argv": [
    "/usr/local/share/jupyter/kernels/spark_python_yarn_cluster/bin/run.sh",
    "--RemoteProcessProxy.kernel-id",
    "{kernel_id}",
    "--RemoteProcessProxy.response-address",
    "{response_address}",
    "--RemoteProcessProxy.public-key",
    "{public_key}",
    "--RemoteProcessProxy.port-range",
    "{port_range}",
    "--RemoteProcessProxy.spark-context-initialization-mode",
    "lazy"
  ]
}

```

![截屏2021-08-19 下午8 30 24](https://user-images.githubusercontent.com/4393648/130070852-9443285b-fe30-482b-8042-69f4d403acea.png)

![截屏2021-08-19 下午8 30 32](https://user-images.githubusercontent.com/4393648/130070912-eb44c62f-5f2b-4aec-95c7-56606c86fce5.png)

## Environment

- Enterprise Gateway Version [2.5]
- Platform: [YARN]

**Comment by kevin-bates** [comment]
It's not clear to me what is required for code completion to work but I believe this is a matter of configuration.

Is this particular kernel instance running on a remote node?  If so, does that node have the same packages?
When running in client mode, are you using the `DistributedProcessProxy` and, if so, what node is the kernel running on?

@lresende or @karlaspuldaro - do you know what additional resources/packages are required to enable code completion?

**Comment by abzymeinsjtu** [comment]
yes, i use YarnClusterProcessProxy to run this kernel, and ensure all node share the same python environment.

it's a little weird that object completion is ok while function completion broken

**Comment by kevin-bates** [comment]
> it's a little weird that object completion is ok while function completion broken

Wait, _some_ aspects of IntelliSense are working?  For my own understanding, what is the difference between _object completion_ and _function completion_?

What process proxy are you using for YARN Client Mode and is the kernel running local or remote to EG?  If you're using the `DistributedProcessProxy` have you configured `--EnterpriseGatewayApp.remote_hosts` (or `EG_REMOTE_HOSTS`) such  nodes other than `localhost` are used?  Remote nodes will require some SSH setup and I'm curious if you see the same issues using YARN Client Mode from non-local nodes.

**Comment by karlaspuldaro** [comment]
It could be the case that autocomplete is taking too long when parsing certain libraries in cluster mode.
One (possible) solution could be disabling `jedi` by adding this to your kernel config `Completer.use_jedi = False`
(or to the top of your notebook `%config Completer.use_jedi = False`)

**Comment by abzymeinsjtu** [comment]
@karlaspuldaro 

thx for the reply. 

I tried to enable the jedi debug mode and got such an error

```
import requests

requests.Oops Jedi has crashed, please report a bug with the following:
"""
[Errno 13] Permission denied: '/home/.cache'
s"""
```  

Seems jedi regard `/home/.cache` as cache directory by default and then trigger this permission issue.

To solve the problem, just configure the `settings.cache_directory` as a writable directory inside the notebook.

**Comment by kevin-bates** [comment]
> To solve the problem, just configure the settings.cache_directory as a writable directory inside the notebook.

@abzymeinsjtu - are you saying the _function completion_ now works or is this merely to resolve the `/home/.cache` permission issue?

**Comment by abzymeinsjtu** [comment]
yes it works now, and the issue can be closed
